## DATA PREPROCESSING

In [40]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix
import datetime as dt
from datetime import datetime

In [3]:
df = pd.read_excel("category.xlsx",sheet_name= [1,4])
loc_to_cat = df[1]
loc_to_cat['category1'] = loc_to_cat['category1'].str.lower()
allUserData = df[4]
#userData = [df[3], df[4], df[5], df[6], df[7]]

#for i in userData[1:]:
#    allUserData = allUserData.append(i)
allUserData.head()

user_id  weekday       date start_time   end_date  end_time  duration  \
0        2        2 2020-06-29   16:00:00 2020-06-29  19:00:00  03:00:00   
1        2        2 2020-06-29   19:00:00 2020-06-29  20:00:00  01:00:00   
2        2        2 2020-06-29   20:00:00 2020-06-29  20:30:00  00:30:00   
3        2        2 2020-06-29   20:30:00 2020-06-29  21:30:00  01:00:00   
4        2        2 2020-06-29   21:30:00 2020-06-29  23:30:00  02:00:00   

   category  category_id location_name location_category my_place  \
0   meeting           13           路易莎              cafe      NaN   
1      food            1        全哥鵝肉小炒        restaurant      NaN   
2   leisure           10           NaN               NaN     home   
3  shopping           12       Miramar     Shopping mall      NaN   
4     study            5           NaN               NaN     home   

   location_id  place_id  
0          4.0       NaN  
1          5.0       NaN  
2          NaN       1.0  
3          6.0       NaN  
4          NaN       1.0

In [4]:
allUserData['location']= allUserData['location_id'].combine_first(allUserData['place_id'])
#drop commute
indexNames = allUserData[(allUserData['category_id'] == 17) ].index
allUserData.drop(indexNames,inplace=True)

allUserData['location'].fillna("99", inplace = True)
allUserData = allUserData.drop(['date','end_date','end_time','location_name','location_category','my_place','location_id','place_id'], 1)
allUserData = allUserData.reset_index(drop = True)

In [5]:
def get_hours(ts):
    a = ts.hour
    return a

def get_mins(ts):
    a = ts.minute
    return a

def get_duration(ts):
    a = ts.hour*60 + ts.minute
    return a 

#allUserData['start_mins'] = allUserData['start_time'].apply(get_mins)
allUserData['start_time'] = allUserData['start_time'].apply(get_duration)
allUserData['duration'] = allUserData['duration'].apply(get_duration)
allUserData = allUserData[['user_id','weekday','start_time','duration','location','category','category_id']]
allUserData.tail()

user_id  weekday  start_time  duration location category  category_id
444        2        5          50       495        1    sleep            3
445        2        5         545        15        1  leisure           10
446        2        5         570       150        2     work            6
447        2        5         780       360        3  meeting           13
448        2        5        1200       240        1  leisure           10

## Random Forest Model

In [6]:
train_df = allUserData.loc[0:299]
test_df = allUserData.loc[300:]
print("Number of traing data is :",len(train_df))
print("Number of testing data is :",len(test_df))

Number of traing data is : 300
Number of testing data is : 149


In [7]:
# without diff
X_train = train_df.iloc[:, np.r_[0:4]].values
y_train = train_df.iloc[:, 6].values

X_test = test_df.iloc[:, np.r_[0:4]].values
y_test = test_df.iloc[:, 6].values

In [8]:
clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0,
            warm_start=False)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [9]:
clf.score(X_test, y_test)

0.6308724832214765

In [10]:
imp = clf.feature_importances_
imp

array([0.        , 0.11707604, 0.48461265, 0.3983113 ])

In [11]:
predictions = clf.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.36      0.71      0.48        21
           3       1.00      0.95      0.97        19
           4       0.00      0.00      0.00         0
           6       0.50      0.82      0.62        11
           9       0.80      0.80      0.80         5
          10       0.80      0.71      0.75        58
          11       0.50      0.12      0.20         8
          12       0.44      0.25      0.32        16
          13       1.00      0.33      0.50         6
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         3

   micro avg       0.63      0.63      0.63       149
   macro avg       0.49      0.43      0.42       149
weighted avg       0.67      0.63      0.62       149



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [12]:
print(confusion_matrix(y_test,predictions))

[[15  0  0  0  0  4  1  1  0  0  0]
 [ 0 18  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  1  0  0  0  1  0]
 [ 0  0  0  0  4  1  0  0  0  0  0]
 [ 8  0  1  5  0 41  0  3  0  0  0]
 [ 5  0  0  0  0  2  1  0  0  0  0]
 [10  0  0  0  1  1  0  4  0  0  0]
 [ 0  0  0  4  0  0  0  0  2  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  1  0  0  0]]


In [13]:
predictions

array([12,  1,  1, 10, 10, 10,  3, 10, 10,  1, 10, 11,  1,  1,  4, 10,  3,
       10,  6, 10, 10, 10, 10,  1,  6,  1, 12, 10, 10,  3,  6,  6, 10,  9,
       10,  3,  6,  1,  1, 13, 10, 10,  9, 10,  3,  6,  6,  1, 10, 10,  3,
       10,  1,  1, 12,  1,  1, 11,  1, 10,  3, 10,  3, 10, 12, 12,  1,  6,
        1,  1, 12,  1, 10,  3, 10,  6,  1, 10, 12,  9, 10,  3,  6,  6,  1,
       10,  9, 10, 10,  3, 10,  6,  1, 13,  1,  1,  1, 10, 10,  3, 10,  1,
       16,  1, 10,  3, 10,  1,  1, 10,  1,  1,  1, 10,  3, 10,  1, 10, 12,
       10,  3, 10,  6,  1, 12, 10,  3, 10,  1,  6,  1, 10,  3,  6,  6,  1,
        1,  1,  1,  1,  1, 10,  9, 10,  3, 10,  6,  6, 10])

## User Data

In [142]:
location = pd.read_csv("hsieh.csv")
location.tail()

location_id  user_id   longitude   latitude  start_date start_time  \
290          291        1  120.456609  23.445741  2020-10-01      16:44   
291          292        1  120.456894  23.445873  2020-10-01      19:15   
292          293        1  120.456551  23.445965  2020-10-01      19:29   
293          294        1  120.456822  23.445649  2020-10-01      19:43   
294          295        1  120.456809  23.445631  2020-10-01      21:56   

     duration  weekday      name1      name2      name3       name4  \
290       NaN        5       長吉本舖  素齋麵食館(素食)  全家(中埔中華店)       芭那那早餐   
291       NaN        5      芭那那早餐  素齋麵食館(素食)  全家(中埔中華店)        長吉本舖   
292       NaN        5  素齋麵食館(素食)      芭那那早餐     嘉陽電腦剌繡   全家(中埔中華店)   
293       NaN        5      芭那那早餐  素齋麵食館(素食)     嘉陽電腦剌繡        平實乙村   
294       NaN        5      芭那那早餐  素齋麵食館(素食)       平實乙村  Sanhe Park   

          name5   category1   category2           category3  \
290  Sanhe Park      Bakery  Restaurant   Convenience store   
291  Sanhe Park  Restaurant  Restaurant   Convenience store   
292        長吉本舖  Restaurant  Restaurant  Embroidery service   
293  Sanhe Park  Restaurant  Restaurant  Embroidery service   
294        長吉本舖  Restaurant  Restaurant   Townhouse complex   

             category4          category5  
290         Restaurant               Park  
291             Bakery               Park  
292  Convenience store             Bakery  
293  Townhouse complex               Park  
294               Park  Townhouse complex

In [143]:
stopLoc = location.drop(['category3','category4','category5'], 1)

# def string_to_mins(ts):
#     a = int(ts.split(':')[0])
#     b = int(ts.split(':')[1])
#     c = a*60 + b
#     return c

#stopLoc['start_time'] = pd.to_datetime(stopLoc['start_time'], format='%H:%M', errors='ignore').apply(string_to_mins)
stopLoc['longitude'] = round(stopLoc['longitude'],2)
stopLoc['latitude'] = round(stopLoc['latitude'],3)
stopLoc = stopLoc.loc[stopLoc['name1'] != 'nccu dorm9']
stopLoc = stopLoc.reset_index(drop = True) 

In [144]:
def deleteEnter(x):
    enterList = []
    dropList = []

    for a in range(len(stopLoc)):

        #如果這筆是「enter」，記住編號
        if (x.iloc[a,14] == 'entering myPlace'):
            enterList.append(a)

        #如果這筆是「exit」，清空enterList
        elif (x.iloc[a,14] == 'exiting myPlace'):
            enterList = []

        elif (enterList == []):
            pass

        #如果這筆不是進去也不是出來，且有enterList，為要刪除的東西
        elif (enterList != []):
            dropList.append(a) 

    x = x.drop(dropList)
    x = x.reset_index(drop = True)  
    return(x)

stopLoc = deleteEnter(stopLoc)
stopLoc

location_id  user_id  longitude  latitude  start_date start_time  \
0              1        1     121.47    25.023  2020-09-21      21:14   
1             14        1     121.47    25.023  2020-09-22      11:25   
2             15        1     121.47    25.022  2020-09-22      11:26   
3             16        1     121.54    25.041  2020-09-22      12:02   
4             17        1     121.54    25.041  2020-09-22      12:04   
5             18        1     121.56    25.004  2020-09-22      12:12   
6             19        1     121.58    24.998  2020-09-22      12:14   
7             20        1     121.58    24.990  2020-09-22      12:20   
8             21        1     121.58    24.987  2020-09-22      12:22   
9             28        1     121.58    24.987  2020-09-22      17:55   
10            31        1     121.58    24.987  2020-09-22      20:56   
11            32        1     121.58    24.987  2020-09-22      20:59   
12            33        1     121.58    24.987  2020-09-22      21:03   
13            34        1     121.58    24.987  2020-09-22      21:41   
14            35        1     121.58    24.987  2020-09-22      22:15   
15            42        1     121.58    24.987  2020-09-23       9:03   
16            43        1     121.58    24.987  2020-09-23      09:10   
17            44        1     121.58    24.986  2020-09-23      09:12   
18            45        1     121.58    24.986  2020-09-23      11:30   
19            46        1     121.58    24.986  2020-09-23      11:35   
20            47        1     121.58    24.987  2020-09-23      12:13   
21            48        1     121.57    24.987  2020-09-23      12:15   
22            49        1     121.58    24.986  2020-09-23      13:29   
23            50        1     121.58    24.986  2020-09-23      13:29   
24            51        1     121.58    24.986  2020-09-23      14:54   
25            52        1     121.58    24.988  2020-09-23      17:55   
26            53        1     121.58    24.987  2020-09-23      18:02   
27            54        1     121.57    24.988  2020-09-23      18:04   
28            55        1     121.57    24.988  2020-09-23      18:01   
29            56        1     121.56    24.990  2020-09-23      18:09   
30            57        1     121.56    24.996  2020-09-23      18:18   
31            58        1     121.55    25.001  2020-09-23      18:21   
32            59        1     121.54    25.001  2020-09-23      18:25   
33            60        1     121.54    25.010  2020-09-23      18:31   
34            61        1     121.54    25.014  2020-09-23      18:36   
35            62        1     121.54    25.012  2020-09-23      18:50   
36            63        1     121.54    25.012  2020-09-23      19:52   
37            64        1     121.54    25.013  2020-09-23      22:06   
38            65        1     121.53    25.015  2020-09-23      22:12   
39            66        1     121.54    25.007  2020-09-23      22:19   
40            67        1     121.56    25.000  2020-09-23      22:21   
41            68        1     121.56    24.991  2020-09-23      22:29   
42            69        1     121.57    24.989  2020-09-23      22:32   
43            70        1     121.57    24.987  2020-09-23      22:37   
44            71        1     121.58    24.987  2020-09-23      22:41   
45            74        1     121.58    24.987  2020-09-23      22:50   
46            78        1     121.58    24.987  2020-09-24      11:43   
47            79        1     121.58    24.987  2020-09-24      11:44   
48            80        1     121.58    24.988  2020-09-24      11:46   
49            81        1     121.58    24.988  2020-09-24      11:47   
50            82        1     121.58    24.987  2020-09-24      11:48   
51            83        1     121.58    24.987  2020-09-24      12:35   
52            84        1     121.58    24.987  2020-09-24      12:37   
53            85        1     121.58    24.987  2020-09-24     

In [145]:
for row in range(0,len(stopLoc)-1): 

    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b

#delete trivial data, 重複地點太多刪除
dropList = []
for row in range(1,len(stopLoc)-1): 
    if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
        
        #same longitude and lantitude
        #if stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2] and stopLoc.iloc[row,3] == stopLoc.iloc[row-1,3]:
        #    dropList.append(row)

        #compared with the last record, over 2 place name duplicated will be deleted
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        #if stopLoc.iloc[row-1,6] < pd.Timedelta('00:10:00'):
        print(res)
        if len(res) > 1: 
            dropList.append(row)

stopLoc = stopLoc.drop(dropList)
stopLoc = stopLoc.reset_index(drop = True)
stopLoc

set()
set()
set()
set()
set()
set()
set()
{'NCCU College of Commerce', '政大四維堂', 'National Chengchi University', '政大行政大樓'}
{'NCCU College of Commerce', '政大四維堂', 'National Chengchi University', '政大行政大樓'}
set()
{'NCCU College of Commerce', '國立政治大學商學院圖書分館', '萊爾富便利商店'}
{'國立政治大學商學院圖書分館', '萊爾富便利商店'}
{'國立政治大學圖書館', '國立政治大學商學院', '萊爾富便利商店', '國立政治大學商學院圖書分館', '國立政治大學'}
{'國立政治大學商學院', '國立政治大學'}
set()
set()
{'國立政治大學商學院圖書分館', '萊爾富便利商店'}
{'國立政治大學商學院圖書分館', '國立政治大學圖書館', '國立政治大學商學院', '萊爾富便利商店'}
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{'臺灣法國文化協會(臺北)', '國立臺灣大學 進修推廣學院', 'Taiwan Power Research Institute', '百老匯影城'}
set()
set()
set()
set()
set()
set()
set()
set()
{'National Chengchi University', '金鮨日式料理', '滇味廚房'}
{'大汗麻辣鴨血臭豆腐(政大店)', '7-Eleven', '滇味廚房'}
{'大汗麻辣鴨血臭豆腐(政大店)', '7-Eleven', '滇味廚房', '提洛斯義式廚房'}
{'大汗麻辣鴨血臭豆腐(政大店)', 'LAZY PASTA 慵懶義式廚房 政大店', '滇味廚房', '7-Eleven', '提洛斯義式廚房'}
{'大汗麻辣鴨血臭豆腐(政大店)', 'LAZY PASTA 慵懶義式廚房 政大店', '滇味廚房', '7-Eleven', '提洛斯義式廚房'}
set()
set()
{'國立政治大學圖書館', '國立政治大學商學院', 

location_id  user_id  longitude  latitude  start_date start_time  \
0              1        1     121.47    25.023  2020-09-21      21:14   
1             14        1     121.47    25.023  2020-09-22      11:25   
2             15        1     121.47    25.022  2020-09-22      11:26   
3             16        1     121.54    25.041  2020-09-22      12:02   
4             17        1     121.54    25.041  2020-09-22      12:04   
5             18        1     121.56    25.004  2020-09-22      12:12   
6             19        1     121.58    24.998  2020-09-22      12:14   
7             20        1     121.58    24.990  2020-09-22      12:20   
8             21        1     121.58    24.987  2020-09-22      12:22   
9             28        1     121.58    24.987  2020-09-22      17:55   
10            31        1     121.58    24.987  2020-09-22      20:56   
11            32        1     121.58    24.987  2020-09-22      20:59   
12            35        1     121.58    24.987  2020-09-22      22:15   
13            42        1     121.58    24.987  2020-09-23       9:03   
14            43        1     121.58    24.987  2020-09-23      09:10   
15            48        1     121.57    24.987  2020-09-23      12:15   
16            49        1     121.58    24.986  2020-09-23      13:29   
17            52        1     121.58    24.988  2020-09-23      17:55   
18            53        1     121.58    24.987  2020-09-23      18:02   
19            54        1     121.57    24.988  2020-09-23      18:04   
20            55        1     121.57    24.988  2020-09-23      18:01   
21            56        1     121.56    24.990  2020-09-23      18:09   
22            57        1     121.56    24.996  2020-09-23      18:18   
23            58        1     121.55    25.001  2020-09-23      18:21   
24            59        1     121.54    25.001  2020-09-23      18:25   
25            60        1     121.54    25.010  2020-09-23      18:31   
26            61        1     121.54    25.014  2020-09-23      18:36   
27            62        1     121.54    25.012  2020-09-23      18:50   
28            64        1     121.54    25.013  2020-09-23      22:06   
29            65        1     121.53    25.015  2020-09-23      22:12   
30            66        1     121.54    25.007  2020-09-23      22:19   
31            67        1     121.56    25.000  2020-09-23      22:21   
32            68        1     121.56    24.991  2020-09-23      22:29   
33            69        1     121.57    24.989  2020-09-23      22:32   
34            70        1     121.57    24.987  2020-09-23      22:37   
35            71        1     121.58    24.987  2020-09-23      22:41   
36            74        1     121.58    24.987  2020-09-23      22:50   
37            78        1     121.58    24.987  2020-09-24      11:43   
38            79        1     121.58    24.987  2020-09-24      11:44   
39            85        1     121.58    24.987  2020-09-24      13:02   
40            86        1     121.58    24.987  2020-09-24      13:03   
41            87        1     121.58    24.987  2020-09-24      13:03   
42            88        1     121.58    24.986  2020-09-24      13:05   
43            92        1     121.58    24.986  2020-09-24      15:43   
44            93        1     121.58    24.986  2020-09-24      18:03   
45            96        1     121.58    24.987  2020-09-24      18:07   
46            97        1     121.58    24.988  2020-09-24      18:10   
47            98        1     121.57    24.988  2020-09-24      18:12   
48            99        1     121.57    24.988  2020-09-24      18:14   
49           100        1     121.57    24.988  2020-09-24      18:14   
50           101        1     121.57    24.989  2020-09-24      18:17   
51           102        1     121.58    24.988  2020-09-24      19:55   
52           103        1     121.58    24.987  2020-09-24      20:01   
53           104        1     121.57    24.988  2020-09-24     

In [134]:
pd.set_option('display.max_rows', 5000)

In [135]:
#kill duration < 10 mins, and keep the start of commuting

dropList = []
for row in range(0,len(stopLoc)-1): 

    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b
            
    #kill duration <10
    if pd.Timedelta(stopLoc.iloc[row,6]) < pd.Timedelta('00:10:00'):
        if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
            dropList.append(row)    
            
removeList = []
for i in range(1,len(dropList)-1):
    if dropList[i] - dropList[i-1] < 2:
        removeList.append(dropList[i])

stopLoc = stopLoc.drop(removeList)
stopLoc = stopLoc.reset_index(drop = True)
stopLoc

location_id  user_id  longitude  latitude  start_date start_time  \
0             1        1     121.47    25.023  2020-09-21      21:14   
1            14        1     121.47    25.023  2020-09-22      11:25   
2            15        1     121.47    25.022  2020-09-22      11:26   
3            16        1     121.54    25.041  2020-09-22      12:02   
4            18        1     121.56    25.004  2020-09-22      12:12   
5            21        1     121.58    24.987  2020-09-22      12:22   
6            28        1     121.58    24.987  2020-09-22      17:55   
7            31        1     121.58    24.987  2020-09-22      20:56   
8            35        1     121.58    24.987  2020-09-22      22:15   
9            42        1     121.58    24.987  2020-09-23       9:03   
10           48        1     121.57    24.987  2020-09-23      12:15   
11           49        1     121.58    24.986  2020-09-23      13:29   
12           52        1     121.58    24.988  2020-09-23      17:55   
13           61        1     121.54    25.014  2020-09-23      18:36   
14           62        1     121.54    25.012  2020-09-23      18:50   
15           64        1     121.54    25.013  2020-09-23      22:06   
16           71        1     121.58    24.987  2020-09-23      22:41   
17           74        1     121.58    24.987  2020-09-23      22:50   
18           78        1     121.58    24.987  2020-09-24      11:43   
19           86        1     121.58    24.987  2020-09-24      13:03   
20           87        1     121.58    24.987  2020-09-24      13:03   
21           88        1     121.58    24.986  2020-09-24      13:05   
22           97        1     121.58    24.988  2020-09-24      18:10   
23          100        1     121.57    24.988  2020-09-24      18:14   
24          101        1     121.57    24.989  2020-09-24      18:17   
25          102        1     121.58    24.988  2020-09-24      19:55   
26          104        1     121.57    24.988  2020-09-24      20:01   
27          105        1     121.58    24.987  2020-09-24      20:03   
28          108        1     121.58    24.987  2020-09-24      20:58   
29          109        1     121.57    24.986  2020-09-24      20:58   
30          112        1     121.58    24.987  2020-09-24      22:56   
31          116        1     121.58    24.987  2020-09-25      11:29   
32          117        1     121.58    24.987  2020-09-25      11:53   
33          120        1     121.58    24.987  2020-09-25      15:40   
34          121        1     121.57    24.988  2020-09-25      15:46   
35          122        1     121.58    24.989  2020-09-25      15:53   
36          132        1     121.54    25.036  2020-09-25      16:24   
37          133        1     121.54    25.042  2020-09-25      16:55   
38          135        1     121.47    25.023  2020-09-25      16:59   
39          143        1     121.47    25.023  2020-09-26      16:59   
40          144        1     121.47    25.022  2020-09-26      17:57   
41          149        1     121.46    25.019  2020-09-26      19:22   
42          154        1     121.48    25.017  2020-09-26      19:34   
43          156        1     121.48    25.020  2020-09-26      20:50   
44          160        1     121.47    25.023  2020-09-26      20:56   
45          168        1     121.47    25.023  2020-09-28      18:20   
46          170        1     121.51    25.042  2020-09-28      18:35   
47          171        1     121.53    25.015  2020-09-28      18:54   
48          174        1     121.54    25.012  2020-09-28      19:04   
49          176        1     121.54    25.013  2020-09-28      21:59   
50          177        1     121.54    25.014  2020-09-28      22:02   
51          178        1     121.47    25.023  2020-09-28      22:38   
52          179        1     121.47    25.023  2020-09-28      22:39   
53          184        1     121.47    25.023  2020-09-29      11:20   
54          185        1     121.47    25.02

In [136]:
#delete duplicate:重複進出同地點, 刪時間短的,重算時間
duplicate = []
for row in range(0,len(stopLoc)-1): 
    
    if (stopLoc.iloc[row,14] == 'exiting myPlace') and (stopLoc.iloc[row+2,14] == 'entering myPlace'):
        if (stopLoc.iloc[row,8] == stopLoc.iloc[row+2,8]):
            duplicate.extend([row,row+1,row+2])
    
    #kill duration <10
    if pd.Timedelta(stopLoc.iloc[row,6]) < pd.Timedelta('00:10:00'):
        if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
            duplicate.append(row) 

stopLoc = stopLoc.drop(duplicate)
stopLoc = stopLoc.reset_index(drop = True)
            
for row in range(0,len(stopLoc)-1): 
    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b

stopLoc

location_id  user_id  longitude  latitude  start_date start_time  \
0             1        1     121.47    25.023  2020-09-21      21:14   
1            14        1     121.47    25.023  2020-09-22      11:25   
2            15        1     121.47    25.022  2020-09-22      11:26   
3            16        1     121.54    25.041  2020-09-22      12:02   
4            21        1     121.58    24.987  2020-09-22      12:22   
5            28        1     121.58    24.987  2020-09-22      17:55   
6            31        1     121.58    24.987  2020-09-22      20:56   
7            35        1     121.58    24.987  2020-09-22      22:15   
8            42        1     121.58    24.987  2020-09-23       9:03   
9            48        1     121.57    24.987  2020-09-23      12:15   
10           49        1     121.58    24.986  2020-09-23      13:29   
11           61        1     121.54    25.014  2020-09-23      18:36   
12           62        1     121.54    25.012  2020-09-23      18:50   
13           71        1     121.58    24.987  2020-09-23      22:41   
14           74        1     121.58    24.987  2020-09-23      22:50   
15           78        1     121.58    24.987  2020-09-24      11:43   
16           86        1     121.58    24.987  2020-09-24      13:03   
17           87        1     121.58    24.987  2020-09-24      13:03   
18           88        1     121.58    24.986  2020-09-24      13:05   
19          100        1     121.57    24.988  2020-09-24      18:14   
20          101        1     121.57    24.989  2020-09-24      18:17   
21          104        1     121.57    24.988  2020-09-24      20:01   
22          105        1     121.58    24.987  2020-09-24      20:03   
23          116        1     121.58    24.987  2020-09-25      11:29   
24          117        1     121.58    24.987  2020-09-25      11:53   
25          120        1     121.58    24.987  2020-09-25      15:40   
26          121        1     121.57    24.988  2020-09-25      15:46   
27          132        1     121.54    25.036  2020-09-25      16:24   
28          135        1     121.47    25.023  2020-09-25      16:59   
29          143        1     121.47    25.023  2020-09-26      16:59   
30          144        1     121.47    25.022  2020-09-26      17:57   
31          154        1     121.48    25.017  2020-09-26      19:34   
32          160        1     121.47    25.023  2020-09-26      20:56   
33          168        1     121.47    25.023  2020-09-28      18:20   
34          170        1     121.51    25.042  2020-09-28      18:35   
35          174        1     121.54    25.012  2020-09-28      19:04   
36          177        1     121.54    25.014  2020-09-28      22:02   
37          179        1     121.47    25.023  2020-09-28      22:39   
38          184        1     121.47    25.023  2020-09-29      11:20   
39          185        1     121.47    25.022  2020-09-29      11:21   
40          186        1     121.54    25.041  2020-09-29      11:59   
41          189        1     121.58    24.998  2020-09-29      12:18   
42          191        1     121.58    24.987  2020-09-29      12:33   
43          196        1     121.58    24.987  2020-09-29      17:50   
44          200        1     121.58    24.987  2020-09-29      22:02   
45          202        1     121.58    24.987  2020-09-29      23:53   
46          209        1     121.58    24.987  2020-09-30       9:14   
47          211        1     121.58    24.986  2020-09-30      10:12   
48          214        1     121.58    24.987  2020-09-29      11:50   
49          215        1     121.58    24.987  2020-09-29      22:02   
50          216        1     121.58    24.986  2020-09-30      11:35   
51          225        1     121.48    25.032  2020-09-30      17:12   
52          227        1     121.48    25.033  2020-09-30      17:23   
53          230        1     121.47    25.023  2020-09-30      17:36   
54          232        1     121.47    25.02

In [137]:
#delete trivial data, 重複地點太多刪除

dropList = []
for row in range(1,len(stopLoc)-1): 
    if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
        
        #same longitude and lantitude
        if stopLoc.iloc[row,1] == stopLoc.iloc[row-1,1] and stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2]:
            dropList.append(row)

        #compared with the last record, over 2 place name duplicated will be deleted
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        if len(res) > 1: 
            dropList.append(row)

stopLoc = stopLoc.drop(dropList)
stopLoc = stopLoc.drop(['name3','name4','name5'], 1)
stopLoc = stopLoc.reset_index(drop = True)

for row in range(0,len(stopLoc)-1): 
    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b
stopLoc

location_id  user_id  longitude  latitude  start_date start_time  \
0             1        1     121.47    25.023  2020-09-21      21:14   
1            14        1     121.47    25.023  2020-09-22      11:25   
2            16        1     121.54    25.041  2020-09-22      12:02   
3            21        1     121.58    24.987  2020-09-22      12:22   
4            28        1     121.58    24.987  2020-09-22      17:55   
5            31        1     121.58    24.987  2020-09-22      20:56   
6            35        1     121.58    24.987  2020-09-22      22:15   
7            42        1     121.58    24.987  2020-09-23       9:03   
8            48        1     121.57    24.987  2020-09-23      12:15   
9            49        1     121.58    24.986  2020-09-23      13:29   
10           61        1     121.54    25.014  2020-09-23      18:36   
11           71        1     121.58    24.987  2020-09-23      22:41   
12           74        1     121.58    24.987  2020-09-23      22:50   
13           78        1     121.58    24.987  2020-09-24      11:43   
14           86        1     121.58    24.987  2020-09-24      13:03   
15           87        1     121.58    24.987  2020-09-24      13:03   
16          100        1     121.57    24.988  2020-09-24      18:14   
17          104        1     121.57    24.988  2020-09-24      20:01   
18          105        1     121.58    24.987  2020-09-24      20:03   
19          116        1     121.58    24.987  2020-09-25      11:29   
20          117        1     121.58    24.987  2020-09-25      11:53   
21          120        1     121.58    24.987  2020-09-25      15:40   
22          121        1     121.57    24.988  2020-09-25      15:46   
23          132        1     121.54    25.036  2020-09-25      16:24   
24          135        1     121.47    25.023  2020-09-25      16:59   
25          143        1     121.47    25.023  2020-09-26      16:59   
26          154        1     121.48    25.017  2020-09-26      19:34   
27          160        1     121.47    25.023  2020-09-26      20:56   
28          168        1     121.47    25.023  2020-09-28      18:20   
29          170        1     121.51    25.042  2020-09-28      18:35   
30          174        1     121.54    25.012  2020-09-28      19:04   
31          179        1     121.47    25.023  2020-09-28      22:39   
32          184        1     121.47    25.023  2020-09-29      11:20   
33          186        1     121.54    25.041  2020-09-29      11:59   
34          189        1     121.58    24.998  2020-09-29      12:18   
35          191        1     121.58    24.987  2020-09-29      12:33   
36          196        1     121.58    24.987  2020-09-29      17:50   
37          200        1     121.58    24.987  2020-09-29      22:02   
38          202        1     121.58    24.987  2020-09-29      23:53   
39          209        1     121.58    24.987  2020-09-30       9:14   
40          214        1     121.58    24.987  2020-09-29      11:50   
41          215        1     121.58    24.987  2020-09-29      22:02   
42          225        1     121.48    25.032  2020-09-30      17:12   
43          230        1     121.47    25.023  2020-09-30      17:36   
44          232        1     121.47    25.023  2020-09-30      18:14   
45          235        1     121.55    25.042  2020-09-30      18:41   
46          247        1     121.47    25.023  2020-10-01       3:15   
47          250        1     121.47    25.023  2020-10-01      10:03   
48          253        1     121.48    25.002  2020-10-01      10:23   
49          270        1     120.64    24.189  2020-10-01      11:59   
50          273        1     120.69    24.171  2020-10-01      12:16   
51          282        1     120.54    23.609  2020-10-01      15:23   
52          290        1     120.46    23.449  2020-10-01      16:33   
53          295        1     120.46    23.446  2020-10-01      21:56   

          duration  weekday                

In [138]:
#標commute
twtymin = pd.Timedelta('00:20:00')

for row in range(0,len(stopLoc)-1): 

    if stopLoc.iloc[row,11] != 'entering myPlace':
        #mark as commute if distance bigger than 500 meters. 
        if (abs(stopLoc.iloc[row+1,2] - stopLoc.iloc[row,2]) + abs(stopLoc.iloc[row+1,3] - stopLoc.iloc[row,3])) > 0.04:
            stopLoc.iloc[row,10] = 'commute'
            
#         elif (abs(stopLoc.iloc[row-1,1] - stopLoc.iloc[row,1]) + abs(stopLoc.iloc[row-1,2] - stopLoc.iloc[row,2])) > 0.02:
#             stopLoc.iloc[row,7] = 'commute'
            
        if stopLoc.iloc[row,11] == 'exiting myPlace':
            stopLoc.iloc[row,10] = 'commute' 
            
        if pd.Timedelta(stopLoc.iloc[row-1,6]) > twtymin :
            if abs(stopLoc.iloc[row-1,2] - stopLoc.iloc[row,2]) > 0.02 or abs(stopLoc.iloc[row-1,3] - stopLoc.iloc[row,3]) > 0.02:
                stopLoc.iloc[row,10] = 'commute'        
        
stopLoc

location_id  user_id  longitude  latitude  start_date start_time  \
0             1        1     121.47    25.023  2020-09-21      21:14   
1            14        1     121.47    25.023  2020-09-22      11:25   
2            16        1     121.54    25.041  2020-09-22      12:02   
3            21        1     121.58    24.987  2020-09-22      12:22   
4            28        1     121.58    24.987  2020-09-22      17:55   
5            31        1     121.58    24.987  2020-09-22      20:56   
6            35        1     121.58    24.987  2020-09-22      22:15   
7            42        1     121.58    24.987  2020-09-23       9:03   
8            48        1     121.57    24.987  2020-09-23      12:15   
9            49        1     121.58    24.986  2020-09-23      13:29   
10           61        1     121.54    25.014  2020-09-23      18:36   
11           71        1     121.58    24.987  2020-09-23      22:41   
12           74        1     121.58    24.987  2020-09-23      22:50   
13           78        1     121.58    24.987  2020-09-24      11:43   
14           86        1     121.58    24.987  2020-09-24      13:03   
15           87        1     121.58    24.987  2020-09-24      13:03   
16          100        1     121.57    24.988  2020-09-24      18:14   
17          104        1     121.57    24.988  2020-09-24      20:01   
18          105        1     121.58    24.987  2020-09-24      20:03   
19          116        1     121.58    24.987  2020-09-25      11:29   
20          117        1     121.58    24.987  2020-09-25      11:53   
21          120        1     121.58    24.987  2020-09-25      15:40   
22          121        1     121.57    24.988  2020-09-25      15:46   
23          132        1     121.54    25.036  2020-09-25      16:24   
24          135        1     121.47    25.023  2020-09-25      16:59   
25          143        1     121.47    25.023  2020-09-26      16:59   
26          154        1     121.48    25.017  2020-09-26      19:34   
27          160        1     121.47    25.023  2020-09-26      20:56   
28          168        1     121.47    25.023  2020-09-28      18:20   
29          170        1     121.51    25.042  2020-09-28      18:35   
30          174        1     121.54    25.012  2020-09-28      19:04   
31          179        1     121.47    25.023  2020-09-28      22:39   
32          184        1     121.47    25.023  2020-09-29      11:20   
33          186        1     121.54    25.041  2020-09-29      11:59   
34          189        1     121.58    24.998  2020-09-29      12:18   
35          191        1     121.58    24.987  2020-09-29      12:33   
36          196        1     121.58    24.987  2020-09-29      17:50   
37          200        1     121.58    24.987  2020-09-29      22:02   
38          202        1     121.58    24.987  2020-09-29      23:53   
39          209        1     121.58    24.987  2020-09-30       9:14   
40          214        1     121.58    24.987  2020-09-29      11:50   
41          215        1     121.58    24.987  2020-09-29      22:02   
42          225        1     121.48    25.032  2020-09-30      17:12   
43          230        1     121.47    25.023  2020-09-30      17:36   
44          232        1     121.47    25.023  2020-09-30      18:14   
45          235        1     121.55    25.042  2020-09-30      18:41   
46          247        1     121.47    25.023  2020-10-01       3:15   
47          250        1     121.47    25.023  2020-10-01      10:03   
48          253        1     121.48    25.002  2020-10-01      10:23   
49          270        1     120.64    24.189  2020-10-01      11:59   
50          273        1     120.69    24.171  2020-10-01      12:16   
51          282        1     120.54    23.609  2020-10-01      15:23   
52          290        1     120.46    23.449  2020-10-01      16:33   
53          295        1     120.46    23.446  2020-10-01      21:56   

          duration  weekday                

In [102]:
stopLoc = stopLoc.drop(['location_id','user_id','longitude','latitude'], 1)
stopLoc

start_date start_time         duration  weekday  \
0    2020-08-20      13:01          0:21:00        5   
1    2020-08-20      13:22          4:52:00        5   
2    2020-08-20      18:14          3:38:00        5   
3    2020-08-20      21:52          0:28:00        5   
4    2020-08-20      22:20          3:37:00        5   
5    2020-08-21       1:57          9:53:00        6   
6    2020-08-21      11:50          1:25:00        6   
7    2020-08-21      13:15          2:49:00        6   
8    2020-08-21      16:04          1:42:00        6   
9    2020-08-21      17:46          0:15:00        6   
10   2020-08-21      18:01          0:15:00        6   
11   2020-08-21      18:16          0:26:00        6   
12   2020-08-21      18:42          0:51:00        6   
13   2020-08-21      19:33          1:03:00        6   
14   2020-08-21      20:36          0:16:00        6   
15   2020-08-21      20:52          0:13:00        6   
16   2020-08-21      21:05         15:33:00        6   
17   2020-08-22      12:38          0:15:00        7   
18   2020-08-22      12:53          1:18:00        7   
19   2020-08-22      14:11          3:47:00        7   
20   2020-08-22      17:58          0:59:00        7   
21   2020-08-22      18:57          0:40:00        7   
22   2020-08-22      19:37          1:09:00        7   
23   2020-08-22      20:46          0:26:00        7   
24   2020-08-22      21:12          1:12:00        7   
25   2020-08-22      22:24          2:31:00        7   
26   2020-08-23       0:55          0:23:00        1   
27   2020-08-23       1:18          0:15:00        1   
28   2020-08-23       1:33         12:32:00        1   
29   2020-08-23      14:05          3:11:00        1   
30   2020-08-23      17:16          1:52:00        1   
31   2020-08-23      19:08          0:56:00        1   
32   2020-08-23      20:04          0:43:00        1   
33   2020-08-23      20:47          0:35:00        1   
34   2020-08-23      21:22          0:25:00        1   
35   2020-08-23      21:47          2:54:00        1   
36   2020-08-24       0:41          9:52:00        2   
37   2020-08-24      10:33          6:56:00        2   
38   2020-08-24      17:29          0:52:00        2   
39   2020-08-24      18:21          1:11:00        2   
40   2020-08-24      19:32          0:17:00        2   
41   2020-08-24      19:49          2:25:00        2   
42   2020-08-24      22:14          1:06:00        2   
43   2020-08-24      23:20          0:32:00        2   
44   2020-08-24      23:52          0:28:00        2   
45   2020-08-25       0:20          9:34:00        3   
46   2020-08-25       9:54          1:02:00        3   
47   2020-08-25      10:56          2:52:00        3   
48   2020-08-25      13:48          5:07:00        3   
49   2020-08-25      18:55          3:06:00        3   
50   2020-08-25      22:01          0:18:00        3   
51   2020-08-25      22:19         14:39:00        3   
52   2020-08-26      12:58          4:27:00        4   
53   2020-08-26      17:25          4:05:00        4   
54   2020-08-26      21:30         12:01:00        4   
55   2020-08-27       9:31          3:25:00        5   
56   2020-08-27      12:56          0:15:00        5   
57   2020-08-27      13:11          9:29:00        5   
58   2020-08-27      22:40         13:16:00        5   
59   2020-08-28      11:56          1:12:00        6   
60   2020-08-28      13:08          0:40:00        6   
61   2020-08-28      13:48          1:09:00        6   
62   2020-08-28      14:57          0:36:00        6   
63   2020-08-28      15:33          1:27:00        6   
64   2020-08-28      17:00          5:03:00        6   
65   2020-08-28      22:03          0:10:00        6   
66   2020-08-28      22:13         18:56:00        6   
67   2020-08-31      17:09          0:31:00        2   
68   2020-08-31      17:40         22:56:00        2   
69   2020-09-03      16:36          1:59:00        5   
70   2020-09-03      18:35   

## Map Category

In [ ]:
stopLoc = pd.merge(stopLoc, loc_to_cat, how='left', on='category1' )
stopLoc = stopLoc.drop(['name1','category1','location_id'],1)
stopLoc['user_id'] = 2
stopLoc = stopLoc[['user_id','weekday','start_time','duration','location']]
stopLoc
#把start_date加回來
#name1,category1拿掉 place_cat對表換成數字

In [ ]:
traing = stopLoc.iloc[:, np.r_[0:4]].values
predictions = clf.predict(traing)

## Myplace

In [ ]:
savedplace = pd.read_csv("savedPlace.csv")
savedplace['place_longitude'] = round(saveplace['place_longitude'],3)
savedplace['place_latitude'] = round(saveplace['place_latitude'],3)
#savedplace = savedplace.loc[savedplace['my_place'] == 1]
savedplace = savedplace.drop(['place_name','my_place','place_id'],1)
savedplace = savedplace.rename(columns={"place_longitude": "longitude", "place_latitude": "latitude"})
savedplace = savedplace.drop_duplicates(subset=['longitude', 'latitude'], keep='last')
savedplace.head()

In [ ]:
stopLoc = pd.merge(stopLoc, savedplace, how='left', on=['longitude','latitude'])
stopLoc