## DATA PREPROCESSING

In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [17]:
df = pd.read_excel("category.xlsx",sheet_name= [1,4])
loc_to_cat = df[1]
loc_to_cat['category1'] = loc_to_cat['category1'].str.lower()
allUserData = df[4]
#userData = [df[3], df[4], df[5], df[6], df[7]]

#for i in userData[1:]:
#    allUserData = allUserData.append(i)
allUserData.head()

user_id  weekday       date start_time   end_date  end_time  duration  \
0        2        2 2020-06-29   16:00:00 2020-06-29  19:00:00  03:00:00   
1        2        2 2020-06-29   19:00:00 2020-06-29  20:00:00  01:00:00   
2        2        2 2020-06-29   20:00:00 2020-06-29  20:30:00  00:30:00   
3        2        2 2020-06-29   20:30:00 2020-06-29  21:30:00  01:00:00   
4        2        2 2020-06-29   21:30:00 2020-06-29  23:30:00  02:00:00   

   category  category_id location_name location_category my_place  \
0   meeting           13           路易莎              cafe      NaN   
1      food            1        全哥鵝肉小炒        restaurant      NaN   
2   leisure           10           NaN               NaN     home   
3  shopping           12       Miramar     Shopping mall      NaN   
4     study            5           NaN               NaN     home   

   location_id  place_id  
0          4.0       NaN  
1          5.0       NaN  
2          NaN       1.0  
3          6.0       NaN  
4          NaN       1.0

In [18]:
allUserData['location']= allUserData['location_id'].combine_first(allUserData['place_id'])
#drop commute
indexNames = allUserData[(allUserData['category_id'] == 17) ].index
allUserData.drop(indexNames,inplace=True)

allUserData['location'].fillna("99", inplace = True)
allUserData = allUserData.drop(['date','end_date','end_time','location_name','location_category','my_place','location_id','place_id'], 1)
allUserData = allUserData.reset_index(drop = True)

In [19]:
def get_hours(ts):
    a = ts.hour
    return a

def get_mins(ts):
    a = ts.minute
    return a

def get_duration(ts):
    a = ts.hour*60 + ts.minute
    return a 

#allUserData['start_mins'] = allUserData['start_time'].apply(get_mins)
allUserData['start_time'] = allUserData['start_time'].apply(get_duration)
allUserData['duration'] = allUserData['duration'].apply(get_duration)
allUserData = allUserData[['user_id','weekday','start_time','duration','location','category','category_id']]
allUserData.tail()

user_id  weekday  start_time  duration location category  category_id
444        2        5          50       495        1    sleep            3
445        2        5         545        15        1  leisure           10
446        2        5         570       150        2     work            6
447        2        5         780       360        3  meeting           13
448        2        5        1200       240        1  leisure           10

## Random Forest Model

In [28]:
train_df = allUserData.loc[0:299]
test_df = allUserData.loc[300:]
print("Number of traing data is :",len(train_df))
print("Number of testing data is :",len(test_df))

Number of traing data is : 300
Number of testing data is : 149


In [29]:
# without diff
X_train = train_df.iloc[:, np.r_[0:4]].values
y_train = train_df.iloc[:, 6].values

X_test = test_df.iloc[:, np.r_[0:4]].values
y_test = test_df.iloc[:, 6].values

In [30]:
clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0,
            warm_start=False)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [31]:
clf.score(X_test, y_test)

0.6308724832214765

In [32]:
imp = clf.feature_importances_
imp

array([0.        , 0.11707604, 0.48461265, 0.3983113 ])

In [26]:
predictions = clf.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.36      0.71      0.48        21
           3       1.00      0.95      0.97        19
           4       0.00      0.00      0.00         0
           6       0.50      0.82      0.62        11
           9       0.80      0.80      0.80         5
          10       0.80      0.71      0.75        58
          11       0.50      0.12      0.20         8
          12       0.44      0.25      0.32        16
          13       1.00      0.33      0.50         6
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         3

   micro avg       0.63      0.63      0.63       149
   macro avg       0.49      0.43      0.42       149
weighted avg       0.67      0.63      0.62       149



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [27]:
print(confusion_matrix(y_test,predictions))

[[15  0  0  0  0  4  1  1  0  0  0]
 [ 0 18  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  1  0  0  0  1  0]
 [ 0  0  0  0  4  1  0  0  0  0  0]
 [ 8  0  1  5  0 41  0  3  0  0  0]
 [ 5  0  0  0  0  2  1  0  0  0  0]
 [10  0  0  0  1  1  0  4  0  0  0]
 [ 0  0  0  4  0  0  0  0  2  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  1  0  0  0]]


In [33]:
predictions

array([12,  1,  1, 10, 10, 10,  3, 10, 10,  1, 10, 11,  1,  1,  4, 10,  3,
       10,  6, 10, 10, 10, 10,  1,  6,  1, 12, 10, 10,  3,  6,  6, 10,  9,
       10,  3,  6,  1,  1, 13, 10, 10,  9, 10,  3,  6,  6,  1, 10, 10,  3,
       10,  1,  1, 12,  1,  1, 11,  1, 10,  3, 10,  3, 10, 12, 12,  1,  6,
        1,  1, 12,  1, 10,  3, 10,  6,  1, 10, 12,  9, 10,  3,  6,  6,  1,
       10,  9, 10, 10,  3, 10,  6,  1, 13,  1,  1,  1, 10, 10,  3, 10,  1,
       16,  1, 10,  3, 10,  1,  1, 10,  1,  1,  1, 10,  3, 10,  1, 10, 12,
       10,  3, 10,  6,  1, 12, 10,  3, 10,  1,  6,  1, 10,  3,  6,  6,  1,
        1,  1,  1,  1,  1, 10,  9, 10,  3, 10,  6,  6, 10])

## User Data

In [110]:
location = pd.read_csv("0908.csv")
location.tail()

location_id   longitude   latitude  start_date start_time  weekday  \
1119         1120  121.522094  25.062802  2020-09-08      11:26        3   
1120         1121  121.522291  25.062872  2020-09-08      11:52        3   
1121         1122  121.522291  25.062872  2020-09-08      11:52        3   
1122         1123  121.522291  25.062872  2020-09-08      11:52        3   
1123         1124  121.522291  25.062872  2020-09-08      11:52        3   

      duration  speed                        name1                     name2  \
1119       0.0   -1.0  LOUISA COFFEE 路易莎咖啡 (民權西門市)             Artco De Cafe   
1120       0.0   -1.0  LOUISA COFFEE 路易莎咖啡 (民權西門市)  Jessie Wa Brunch. Coffee   
1121       0.0   -1.0  LOUISA COFFEE 路易莎咖啡 (民權西門市)  Jessie Wa Brunch. Coffee   
1122       0.0   -1.0  LOUISA COFFEE 路易莎咖啡 (民權西門市)  Jessie Wa Brunch. Coffee   
1123       0.0   -1.0  LOUISA COFFEE 路易莎咖啡 (民權西門市)  Jessie Wa Brunch. Coffee   

              name3                                              name4  \
1119       最佳風情國際婚紗                           Jessie Wa Brunch. Coffee   
1120  Artco De Cafe  Judy Judy cultural and creative wedding photog...   
1121  Artco De Cafe  Judy Judy cultural and creative wedding photog...   
1122  Artco De Cafe  Judy Judy cultural and creative wedding photog...   
1123  Artco De Cafe  Judy Judy cultural and creative wedding photog...   

                                                  name5 category1   category2  \
1119  Judy Judy cultural and creative wedding photog...      cafe        cafe   
1120                                             威成文具批發      cafe  restaurant   
1121                                             威成文具批發      cafe  restaurant   
1122                                             威成文具批發      cafe  restaurant   
1123                                             威成文具批發      cafe  restaurant   

              category3          category4          category5  
1119  point_of_interest         restaurant  point_of_interest  
1120               cafe  point_of_interest  point_of_interest  
1121               cafe  point_of_interest  point_of_interest  
1122               cafe  point_of_interest  point_of_interest  
1123               cafe  point_of_interest  point_of_interest

In [116]:
stopLoc = location.drop(['category3','category4','category5'], 1)

def string_to_mins(ts):
    a = int(ts.split(':')[0])
    b = int(ts.split(':')[1])
    c = a*60 + b
    return c

#stopLoc['start_time'] = pd.to_datetime(stopLoc['start_time'], format='%H:%M', errors='ignore').apply(string_to_mins)
stopLoc['longitude'] = round(stopLoc['longitude'],3)
stopLoc['latitude'] = round(stopLoc['latitude'],3)
stopLoc

location_id  longitude  latitude  start_date start_time  weekday  \
0               1    121.576    24.986  2020/07/22      11:00        4   
1               2    121.443    24.433  2020/07/23      12:00        5   
2               3    121.123    24.765  2020/07/24    13:00\n        6   
3               4    121.563    25.087  2020-09-04      12:10        6   
4               5    121.563    25.087  2020-09-04      12:10        6   
5               6    121.563    25.087  2020-09-04      12:10        6   
6               7    121.563    25.087  2020-09-04      12:10        6   
7               8    121.563    25.087  2020-09-04      12:10        6   
8               9    121.563    25.087  2020-09-04      12:10        6   
9              10    121.563    25.087  2020-09-04      12:11        6   
10             11    121.563    25.087  2020-09-04      12:11        6   
11             12    121.563    25.087  2020-09-04      12:11        6   
12             13    121.563    25.087  2020-09-04      12:11        6   
13             14    121.563    25.087  2020-09-04      12:13        6   
14             15    121.563    25.087  2020-09-04      12:13        6   
15             16    121.563    25.087  2020-09-04      12:13        6   
16             17    121.563    25.087  2020-09-04      12:13        6   
17             18    121.563    25.087  2020-09-04      12:13        6   
18             19    121.563    25.087  2020-09-04      12:14        6   
19             20    121.563    25.087  2020-09-04      12:14        6   
20             21    121.563    25.087  2020-09-04      12:16        6   
21             22    121.563    25.087  2020-09-04      12:16        6   
22             23    121.563    25.087  2020-09-04      12:16        6   
23             24    121.563    25.087  2020-09-04      12:22        6   
24             25    121.563    25.087  2020-09-04      12:22        6   
25             26    121.563    25.087  2020-09-04      12:22        6   
26             27    121.563    25.087  2020-09-04      12:22        6   
27             28    121.563    25.087  2020-09-04      12:25        6   
28             29    121.563    25.087  2020-09-04      12:25        6   
29             30    121.563    25.087  2020-09-04      12:25        6   
...           ...        ...       ...         ...        ...      ...   
1094         1095    121.536    25.078  2020-09-08      10:48        3   
1095         1096    121.536    25.078  2020-09-08      10:48        3   
1096         1097    121.533    25.078  2020-09-08      10:48        3   
1097         1098    121.532    25.078  2020-09-08      10:48        3   
1098         1099    121.530    25.078  2020-09-08      10:48        3   
1099         1100    121.530    25.078  2020-09-08      10:48        3   
1100         1101    121.529    25.078  2020-09-08      10:49        3   
1101         1102    121.528    25.078  2020-09-08      10:49        3   
1102         1103    121.527    25.077  2020-09-08      10:49        3   
1103         1104    121.526    25.077  2020-09-08      10:50        3   
1104         1105    121.525    25.074  2020-09-08      10:50        3   
1105         1106    121.525    25.075  2020-09-08      10:50        3   
1106         1107    121.524    25.073  2020-09-08      10:50        3   
1107         1108    121.523    25.071  2020-09-08      10:50        3   
1108         1109    121.523    25.070  2020-09-08      10:51        3   
1109         1110    121.523    25.069  2020-09-08      10:52        3   
1110         1111    121.523    25.068  2020-09-08      10:52        3   
1111         1112    121.522    25.067  2020-09-08      10:52        3   
1112         1113    121.522    25.066  2020-09-08      10:52        3   
1113         1114    121.522    25.065  2020-09-08      10:52        3   
1114         1115    121.522    25.064  2020-09-08      10:53        3   
1115         1116    121.522    25.064  2020-09-08      10:53        3   
1116      

In [117]:
for i in range(10):
    dropList = []
    for row in range(1,len(stopLoc)-1): 
        if stopLoc.iloc[row-1,14] == 'entering' and stopLoc.iloc[row,14] != 'exiting':
            dropList.append(row)
            
    print(dropList)
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    
stopLoc    

[368, 379, 535, 747, 770, 782, 849, 856, 962, 1056]
[368, 378, 533, 744, 766, 777, 843, 849, 954, 1047]
[377, 531, 741, 762, 772, 837, 842, 946, 1038]
[530, 739, 759, 768, 832, 836, 939, 1030]
[530, 738, 757, 765, 831, 933, 1023]
[530, 737, 755, 827, 928, 1017]
[736, 753, 824, 1012]
[822, 1009]
[822]
[822]


location_id  longitude  latitude  start_date start_time  weekday  \
0               1    121.576    24.986  2020/07/22      11:00        4   
1               2    121.443    24.433  2020/07/23      12:00        5   
2               3    121.123    24.765  2020/07/24    13:00\n        6   
3               4    121.563    25.087  2020-09-04      12:10        6   
4               5    121.563    25.087  2020-09-04      12:10        6   
5               6    121.563    25.087  2020-09-04      12:10        6   
6               7    121.563    25.087  2020-09-04      12:10        6   
7               8    121.563    25.087  2020-09-04      12:10        6   
8               9    121.563    25.087  2020-09-04      12:10        6   
9              10    121.563    25.087  2020-09-04      12:11        6   
10             11    121.563    25.087  2020-09-04      12:11        6   
11             12    121.563    25.087  2020-09-04      12:11        6   
12             13    121.563    25.087  2020-09-04      12:11        6   
13             14    121.563    25.087  2020-09-04      12:13        6   
14             15    121.563    25.087  2020-09-04      12:13        6   
15             16    121.563    25.087  2020-09-04      12:13        6   
16             17    121.563    25.087  2020-09-04      12:13        6   
17             18    121.563    25.087  2020-09-04      12:13        6   
18             19    121.563    25.087  2020-09-04      12:14        6   
19             20    121.563    25.087  2020-09-04      12:14        6   
20             21    121.563    25.087  2020-09-04      12:16        6   
21             22    121.563    25.087  2020-09-04      12:16        6   
22             23    121.563    25.087  2020-09-04      12:16        6   
23             24    121.563    25.087  2020-09-04      12:22        6   
24             25    121.563    25.087  2020-09-04      12:22        6   
25             26    121.563    25.087  2020-09-04      12:22        6   
26             27    121.563    25.087  2020-09-04      12:22        6   
27             28    121.563    25.087  2020-09-04      12:25        6   
28             29    121.563    25.087  2020-09-04      12:25        6   
29             30    121.563    25.087  2020-09-04      12:25        6   
...           ...        ...       ...         ...        ...      ...   
1036         1095    121.536    25.078  2020-09-08      10:48        3   
1037         1096    121.536    25.078  2020-09-08      10:48        3   
1038         1097    121.533    25.078  2020-09-08      10:48        3   
1039         1098    121.532    25.078  2020-09-08      10:48        3   
1040         1099    121.530    25.078  2020-09-08      10:48        3   
1041         1100    121.530    25.078  2020-09-08      10:48        3   
1042         1101    121.529    25.078  2020-09-08      10:49        3   
1043         1102    121.528    25.078  2020-09-08      10:49        3   
1044         1103    121.527    25.077  2020-09-08      10:49        3   
1045         1104    121.526    25.077  2020-09-08      10:50        3   
1046         1105    121.525    25.074  2020-09-08      10:50        3   
1047         1106    121.525    25.075  2020-09-08      10:50        3   
1048         1107    121.524    25.073  2020-09-08      10:50        3   
1049         1108    121.523    25.071  2020-09-08      10:50        3   
1050         1109    121.523    25.070  2020-09-08      10:51        3   
1051         1110    121.523    25.069  2020-09-08      10:52        3   
1052         1111    121.523    25.068  2020-09-08      10:52        3   
1053         1112    121.522    25.067  2020-09-08      10:52        3   
1054         1113    121.522    25.066  2020-09-08      10:52        3   
1055         1114    121.522    25.065  2020-09-08      10:52        3   
1056         1115    121.522    25.064  2020-09-08      10:53        3   
1057         1116    121.522    25.064  2020-09-08      10:53        3   
1058      

In [118]:
#delete trivial data
for i in range(3):
    dropList = []
    for row in range(1,len(stopLoc)-1): 
        if stopLoc.iloc[row,1] == stopLoc.iloc[row-1,1] and stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2]:
            if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
                dropList.append(row)
    
        #compared with the last record, over 2 place name duplicated will be deleted
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        if len(res) > 1: 
            if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
                dropList.append(row)
                
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    
stopLoc

location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.563    25.087  2020-09-04      12:10        6   
4            209    121.562    25.087  2020-09-04      18:08        6   
5            210    121.563    25.087  2020-09-04      18:09        6   
6            211    121.561    25.086  2020-09-04      18:09        6   
7            212    121.560    25.085  2020-09-04      18:09        6   
8            213    121.559    25.085  2020-09-04      18:10        6   
9            214    121.558    25.085  2020-09-04      18:10        6   
10           215    121.557    25.085  2020-09-04      18:10        6   
11           216    121.556    25.085  2020-09-04      18:11        6   
12           218    121.553    25.086  2020-09-04      18:18        6   
13           222    121.549    25.086  2020-09-04      18:20        6   
14           223    121.547    25.069  2020-09-04      18:22        6   
15           226    121.545    25.067  2020-09-04      18:24        6   
16           230    121.544    25.064  2020-09-04      18:25        6   
17           232    121.544    25.060  2020-09-04      18:26        6   
18           234    121.544    25.056  2020-09-04      18:27        6   
19           236    121.544    25.054  2020-09-04      18:27        6   
20           238    121.544    25.052  2020-09-04      18:27        6   
21           243    121.544    25.049  2020-09-04      18:29        6   
22           244    121.544    25.048  2020-09-04      18:29        6   
23           245    121.544    25.046  2020-09-04      18:29        6   
24           247    121.544    25.044  2020-09-04      18:29        6   
25           249    121.544    25.042  2020-09-04      18:29        6   
26           250    121.544    25.041  2020-09-04      18:29        6   
27           251    121.543    25.025  2020-09-04      18:40        6   
28           252    121.544    25.025  2020-09-04      18:42        6   
29           253    121.545    25.025  2020-09-04      18:43        6   
..           ...        ...       ...         ...        ...      ...   
508         1053    121.567    25.086  2020-09-07      21:42        2   
509         1056     25.087    25.087  2020-09-07      21:42        2   
510         1065    121.563    25.087  2020-09-08      10:33        3   
511         1066    121.562    25.085  2020-09-08      10:33        3   
512         1067    121.561    25.084  2020-09-08      10:34        3   
513         1068    121.560    25.085  2020-09-08      10:36        3   
514         1069    121.559    25.085  2020-09-08      10:37        3   
515         1070    121.558    25.085  2020-09-08      10:38        3   
516         1071    121.557    25.085  2020-09-08      10:38        3   
517         1073    121.556    25.085  2020-09-08      10:38        3   
518         1074    121.554    25.085  2020-09-08      10:39        3   
519         1075    121.553    25.085  2020-09-08      10:40        3   
520         1076    121.551    25.086  2020-09-08      10:40        3   
521         1078    121.549    25.084  2020-09-08      10:41        3   
522         1079    121.549    25.083  2020-09-08      10:41        3   
523         1080    121.549    25.082  2020-09-08      10:42        3   
524         1081    121.548    25.081  2020-09-08      10:43        3   
525         1082    121.548    25.080  2020-09-08      10:43        3   
526         1084    121.546    25.080  2020-09-08      10:45        3   
527         1085    121.545    25.080  2020-09-08      10:45        3   
528         1086    121.544    25.080  2020-09-08      10:45        3   
529         1092    121.539    25.076  2020-09-08      10:48        3   
530         1103    121.527    25.077  2020-09-08      10:49   

In [119]:
#calculate duration
import datetime as dt
from datetime import datetime

dropList = []
for row in range(0,len(stopLoc)-1): 
        
    res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
    if len(res) > 1: 
        if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
            dropList.append(row)

    #calculate duration
    if stopLoc.iloc[row+1,3] == stopLoc.iloc[row,3]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,4], '%H:%M') - datetime.strptime(stopLoc.iloc[row,4], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,4].split(':')[0]),int(stopLoc.iloc[row+1,4].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,4].split(':')[0]),int(stopLoc.iloc[row,4].split(':')[1]))
        stopLoc.iloc[row,6] = a - b
            
    #kill duration <10
    if pd.Timedelta(stopLoc.iloc[row,6]) < pd.Timedelta('00:10:00'):
        if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
            dropList.append(row)     


removeList = []
for i in range(1,len(dropList)-1):
    if dropList[i] - dropList[i-1] < 3:
        removeList.append(dropList[i])

stopLoc = stopLoc.drop(removeList)
stopLoc = stopLoc.reset_index(drop = True)

for row in range(0,len(stopLoc)-1): 

    #calculate duration
    if stopLoc.iloc[row+1,3] == stopLoc.iloc[row,3]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,4], '%H:%M') - datetime.strptime(stopLoc.iloc[row,4], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,4].split(':')[0]),int(stopLoc.iloc[row+1,4].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,4].split(':')[0]),int(stopLoc.iloc[row,4].split(':')[1]))
        stopLoc.iloc[row,6] = a - b

stopLoc = stopLoc.drop(['start_date','name2','name3','name4','name5','speed'], 1)
stopLoc

location_id  longitude  latitude start_time  weekday        duration  \
0             1    121.576    24.986      11:00        4  1 day, 1:00:00   
1             2    121.443    24.433      12:00        5  1 day, 1:00:00   
2             3    121.123    24.765    13:00\n        6        23:10:00   
3             4    121.563    25.087      12:10        6         5:58:00   
4           209    121.562    25.087      18:08        6         0:01:00   
5           210    121.563    25.087      18:09        6         0:20:00   
6           250    121.544    25.041      18:29        6         0:14:00   
7           253    121.545    25.025      18:43        6         0:34:00   
8           275    121.528    25.025      19:17        6         0:58:00   
9           276    121.529    25.024      20:15        6         0:23:00   
10          278    121.529    25.023      20:38        6         0:14:00   
11          280    121.528    25.022      20:52        6         0:18:00   
12          283    121.528    25.021      21:10        6         0:47:00   
13          356    121.557    25.083      21:57        6         3:25:00   
14          368     25.087    25.087      01:22        7        11:12:00   
15          371    121.563    25.087      12:34        7         0:00:00   
16          372    121.562    25.085      12:34        7         0:24:00   
17          376     25.087    25.087      12:58        7         0:01:00   
18          377    121.563    25.087      12:59        7         0:01:00   
19          378    121.561    25.086      13:00        7         0:01:00   
20          379     25.087    25.087      13:01        7         0:06:00   
21          383    121.563    25.087      13:07        7         0:05:00   
22          384    121.561    25.085      13:12        7         0:18:00   
23          385    121.560    25.085      13:30        7         0:03:00   
24          388     25.087    25.087      13:33        7         4:24:00   
25          389    121.563    25.087      17:57        7         0:00:00   
26          390    121.560    25.086      17:57        7         0:35:00   
27          458    121.521    25.053      18:32        7         0:34:00   
28          463    121.526    25.052      19:06        7         1:36:00   
29          470    121.521    25.053      20:42        7         0:21:00   
..          ...        ...       ...        ...      ...             ...   
50          747     25.087    25.087      20:27        1         1:12:00   
51          755    121.563    25.087      21:39        1         0:00:00   
52          756    121.560    25.085      21:39        1         0:00:00   
53          764    121.559    25.085      21:39        1         1:21:00   
54          770     25.087    25.087      23:00        1        13:33:00   
55          778    121.563    25.087      12:33        2         0:00:00   
56          779    121.561    25.085      12:33        2         0:08:00   
57          782     25.087    25.087      12:41        2         0:14:00   
58          788    121.563    25.087      12:55        2         0:00:00   
59          789    121.565    25.085      12:55        2         0:21:00   
60          849     25.057    25.057      13:16        2         0:00:00   
61          854    121.616    25.057      13:16        2         0:01:00   
62          855    121.618    25.055      13:17        2         0:01:00   
63          856     25.057    25.057      13:18        2         1:06:00   
64          867    121.616    25.058      14:24        2         2:08:00   
65          872    121.616    25.057      16:32        2         0:21:00   
66          877    121.616    25.057      16:53        2         0:00:00   
67          878    121.618    25.060      16:53        2         0:32:00   
68          962     25.087    25.087      17:25        2         2:30:00   
69          969    121.563    25.087      19:55        2         0:00:00   
70          970    121.560    25.085      19:55     

In [120]:
for row in range(0,len(stopLoc)-1): 

    #calculate duration
    if abs(stopLoc.iloc[row+1,1] - stopLoc.iloc[row,1]) > 0.03 or abs(stopLoc.iloc[row+1,2] - stopLoc.iloc[row,2]) > 0.03:
        if stopLoc.iloc[row,8] != 'entering':
            stopLoc.iloc[row,7] = 'commute'
stopLoc

location_id  longitude  latitude start_time  weekday        duration  \
0             1    121.576    24.986      11:00        4  1 day, 1:00:00   
1             2    121.443    24.433      12:00        5  1 day, 1:00:00   
2             3    121.123    24.765    13:00\n        6        23:10:00   
3             4    121.563    25.087      12:10        6         5:58:00   
4           209    121.562    25.087      18:08        6         0:01:00   
5           210    121.563    25.087      18:09        6         0:20:00   
6           250    121.544    25.041      18:29        6         0:14:00   
7           253    121.545    25.025      18:43        6         0:34:00   
8           275    121.528    25.025      19:17        6         0:58:00   
9           276    121.529    25.024      20:15        6         0:23:00   
10          278    121.529    25.023      20:38        6         0:14:00   
11          280    121.528    25.022      20:52        6         0:18:00   
12          283    121.528    25.021      21:10        6         0:47:00   
13          356    121.557    25.083      21:57        6         3:25:00   
14          368     25.087    25.087      01:22        7        11:12:00   
15          371    121.563    25.087      12:34        7         0:00:00   
16          372    121.562    25.085      12:34        7         0:24:00   
17          376     25.087    25.087      12:58        7         0:01:00   
18          377    121.563    25.087      12:59        7         0:01:00   
19          378    121.561    25.086      13:00        7         0:01:00   
20          379     25.087    25.087      13:01        7         0:06:00   
21          383    121.563    25.087      13:07        7         0:05:00   
22          384    121.561    25.085      13:12        7         0:18:00   
23          385    121.560    25.085      13:30        7         0:03:00   
24          388     25.087    25.087      13:33        7         4:24:00   
25          389    121.563    25.087      17:57        7         0:00:00   
26          390    121.560    25.086      17:57        7         0:35:00   
27          458    121.521    25.053      18:32        7         0:34:00   
28          463    121.526    25.052      19:06        7         1:36:00   
29          470    121.521    25.053      20:42        7         0:21:00   
..          ...        ...       ...        ...      ...             ...   
50          747     25.087    25.087      20:27        1         1:12:00   
51          755    121.563    25.087      21:39        1         0:00:00   
52          756    121.560    25.085      21:39        1         0:00:00   
53          764    121.559    25.085      21:39        1         1:21:00   
54          770     25.087    25.087      23:00        1        13:33:00   
55          778    121.563    25.087      12:33        2         0:00:00   
56          779    121.561    25.085      12:33        2         0:08:00   
57          782     25.087    25.087      12:41        2         0:14:00   
58          788    121.563    25.087      12:55        2         0:00:00   
59          789    121.565    25.085      12:55        2         0:21:00   
60          849     25.057    25.057      13:16        2         0:00:00   
61          854    121.616    25.057      13:16        2         0:01:00   
62          855    121.618    25.055      13:17        2         0:01:00   
63          856     25.057    25.057      13:18        2         1:06:00   
64          867    121.616    25.058      14:24        2         2:08:00   
65          872    121.616    25.057      16:32        2         0:21:00   
66          877    121.616    25.057      16:53        2         0:00:00   
67          878    121.618    25.060      16:53        2         0:32:00   
68          962     25.087    25.087      17:25        2         2:30:00   
69          969    121.563    25.087      19:55        2         0:00:00   
70          970    121.560    25.085      19:55     

## Map Category

In [96]:
stopLoc = pd.merge(stopLoc, loc_to_cat, how='left', on='category1' )
stopLoc = stopLoc.drop(['name1','category1','location_id'],1)
stopLoc['user_id'] = 2
stopLoc = stopLoc[['user_id','weekday','start_time','duration','location']]
stopLoc
#把start_date加回來
#name1,category1拿掉 place_cat對表換成數字

user_id  weekday start_time        duration  location
0         2        4      11:00  1 day, 1:00:00       NaN
1         2        5      12:00  1 day, 1:00:00       NaN
2         2        6    13:00\n        23:10:00       NaN
3         2        6      12:10         5:58:00       5.0
4         2        6      18:08         0:01:00       NaN
5         2        6      18:09         0:20:00       1.0
6         2        6      18:29         0:14:00       NaN
7         2        6      18:43         0:34:00       5.0
8         2        6      19:17         0:58:00      19.0
9         2        6      20:15         0:23:00       NaN
10        2        6      20:38         0:14:00       4.0
11        2        6      20:52         0:18:00       6.0
12        2        6      21:10         0:47:00       NaN
13        2        6      21:57         3:25:00       NaN
14        2        7      01:22        11:12:00       NaN
15        2        7      12:34         0:00:00       1.0
16        2        7      12:34         0:24:00       5.0
17        2        7      12:58         0:01:00       NaN
18        2        7      12:59         0:01:00       1.0
19        2        7      13:00         0:01:00       NaN
20        2        7      13:01         0:06:00       NaN
21        2        7      13:07         0:05:00       1.0
22        2        7      13:12         0:18:00       5.0
23        2        7      13:30         0:03:00       4.0
24        2        7      13:33         4:24:00       NaN
25        2        7      17:57         0:00:00       1.0
26        2        7      17:57         0:35:00       NaN
27        2        7      18:32         0:34:00       NaN
28        2        7      19:06         1:36:00      19.0
29        2        7      20:42         0:21:00       NaN
..      ...      ...        ...             ...       ...
50        2        1      20:27         1:12:00       NaN
51        2        1      21:39         0:00:00       1.0
52        2        1      21:39         0:00:00       NaN
53        2        1      21:39         1:21:00       5.0
54        2        1      23:00        13:33:00       NaN
55        2        2      12:33         0:00:00       1.0
56        2        2      12:33         0:08:00       5.0
57        2        2      12:41         0:14:00       NaN
58        2        2      12:55         0:00:00       1.0
59        2        2      12:55         0:21:00      13.0
60        2        2      13:16         0:00:00       NaN
61        2        2      13:16         0:01:00       NaN
62        2        2      13:17         0:01:00       NaN
63        2        2      13:18         1:06:00       NaN
64        2        2      14:24         2:08:00       NaN
65        2        2      16:32         0:21:00       5.0
66        2        2      16:53         0:00:00       NaN
67        2        2      16:53         0:32:00       NaN
68        2        2      17:25         2:30:00       NaN
69        2        2      19:55         0:00:00       1.0
70        2        2      19:55         0:12:00       NaN
71        2        2      20:07         0:42:00       NaN
72        2        2      20:49         0:53:00       NaN
73        2        2      21:42        12:51:00       NaN
74        2        3      10:33         0:00:00       1.0
75        2        3      10:33         0:19:00       5.0
76        2        3      10:52         0:00:00      13.0
77        2        3      10:52         0:34:00       4.0
78        2        3      11:26         0:26:00       4.0
79        2        3      11:52               0       4.0

[80 rows x 5 columns]

In [ ]:
traing = stopLoc.iloc[:, np.r_[0:4]].values
predictions = clf.predict(traing)

## Myplace

In [ ]:
savedplace = pd.read_csv("savedPlace.csv")
savedplace['place_longitude'] = round(saveplace['place_longitude'],3)
savedplace['place_latitude'] = round(saveplace['place_latitude'],3)
#savedplace = savedplace.loc[savedplace['my_place'] == 1]
savedplace = savedplace.drop(['place_name','my_place','place_id'],1)
savedplace = savedplace.rename(columns={"place_longitude": "longitude", "place_latitude": "latitude"})
savedplace = savedplace.drop_duplicates(subset=['longitude', 'latitude'], keep='last')
savedplace.head()

In [ ]:
stopLoc = pd.merge(stopLoc, savedplace, how='left', on=['longitude','latitude'])
stopLoc