## DATA PREPROCESSING

In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [17]:
df = pd.read_excel("category.xlsx",sheet_name= [1,4])
loc_to_cat = df[1]
loc_to_cat['category1'] = loc_to_cat['category1'].str.lower()
allUserData = df[4]
#userData = [df[3], df[4], df[5], df[6], df[7]]

#for i in userData[1:]:
#    allUserData = allUserData.append(i)
allUserData.head()

user_id  weekday       date start_time   end_date  end_time  duration  \
0        2        2 2020-06-29   16:00:00 2020-06-29  19:00:00  03:00:00   
1        2        2 2020-06-29   19:00:00 2020-06-29  20:00:00  01:00:00   
2        2        2 2020-06-29   20:00:00 2020-06-29  20:30:00  00:30:00   
3        2        2 2020-06-29   20:30:00 2020-06-29  21:30:00  01:00:00   
4        2        2 2020-06-29   21:30:00 2020-06-29  23:30:00  02:00:00   

   category  category_id location_name location_category my_place  \
0   meeting           13           路易莎              cafe      NaN   
1      food            1        全哥鵝肉小炒        restaurant      NaN   
2   leisure           10           NaN               NaN     home   
3  shopping           12       Miramar     Shopping mall      NaN   
4     study            5           NaN               NaN     home   

   location_id  place_id  
0          4.0       NaN  
1          5.0       NaN  
2          NaN       1.0  
3          6.0       NaN  
4          NaN       1.0

In [18]:
allUserData['location']= allUserData['location_id'].combine_first(allUserData['place_id'])
#drop commute
indexNames = allUserData[(allUserData['category_id'] == 17) ].index
allUserData.drop(indexNames,inplace=True)

allUserData['location'].fillna("99", inplace = True)
allUserData = allUserData.drop(['date','end_date','end_time','location_name','location_category','my_place','location_id','place_id'], 1)
allUserData = allUserData.reset_index(drop = True)

In [19]:
def get_hours(ts):
    a = ts.hour
    return a

def get_mins(ts):
    a = ts.minute
    return a

def get_duration(ts):
    a = ts.hour*60 + ts.minute
    return a 

#allUserData['start_mins'] = allUserData['start_time'].apply(get_mins)
allUserData['start_time'] = allUserData['start_time'].apply(get_duration)
allUserData['duration'] = allUserData['duration'].apply(get_duration)
allUserData = allUserData[['user_id','weekday','start_time','duration','location','category','category_id']]
allUserData.tail()

user_id  weekday  start_time  duration location category  category_id
444        2        5          50       495        1    sleep            3
445        2        5         545        15        1  leisure           10
446        2        5         570       150        2     work            6
447        2        5         780       360        3  meeting           13
448        2        5        1200       240        1  leisure           10

## Random Forest Model

In [28]:
train_df = allUserData.loc[0:299]
test_df = allUserData.loc[300:]
print("Number of traing data is :",len(train_df))
print("Number of testing data is :",len(test_df))

Number of traing data is : 300
Number of testing data is : 149


In [29]:
# without diff
X_train = train_df.iloc[:, np.r_[0:4]].values
y_train = train_df.iloc[:, 6].values

X_test = test_df.iloc[:, np.r_[0:4]].values
y_test = test_df.iloc[:, 6].values

In [30]:
clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0,
            warm_start=False)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [31]:
clf.score(X_test, y_test)

0.6308724832214765

In [32]:
imp = clf.feature_importances_
imp

array([0.        , 0.11707604, 0.48461265, 0.3983113 ])

In [26]:
predictions = clf.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.36      0.71      0.48        21
           3       1.00      0.95      0.97        19
           4       0.00      0.00      0.00         0
           6       0.50      0.82      0.62        11
           9       0.80      0.80      0.80         5
          10       0.80      0.71      0.75        58
          11       0.50      0.12      0.20         8
          12       0.44      0.25      0.32        16
          13       1.00      0.33      0.50         6
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         3

   micro avg       0.63      0.63      0.63       149
   macro avg       0.49      0.43      0.42       149
weighted avg       0.67      0.63      0.62       149



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [27]:
print(confusion_matrix(y_test,predictions))

[[15  0  0  0  0  4  1  1  0  0  0]
 [ 0 18  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  1  0  0  0  1  0]
 [ 0  0  0  0  4  1  0  0  0  0  0]
 [ 8  0  1  5  0 41  0  3  0  0  0]
 [ 5  0  0  0  0  2  1  0  0  0  0]
 [10  0  0  0  1  1  0  4  0  0  0]
 [ 0  0  0  4  0  0  0  0  2  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  1  0  0  0]]


In [33]:
predictions

array([12,  1,  1, 10, 10, 10,  3, 10, 10,  1, 10, 11,  1,  1,  4, 10,  3,
       10,  6, 10, 10, 10, 10,  1,  6,  1, 12, 10, 10,  3,  6,  6, 10,  9,
       10,  3,  6,  1,  1, 13, 10, 10,  9, 10,  3,  6,  6,  1, 10, 10,  3,
       10,  1,  1, 12,  1,  1, 11,  1, 10,  3, 10,  3, 10, 12, 12,  1,  6,
        1,  1, 12,  1, 10,  3, 10,  6,  1, 10, 12,  9, 10,  3,  6,  6,  1,
       10,  9, 10, 10,  3, 10,  6,  1, 13,  1,  1,  1, 10, 10,  3, 10,  1,
       16,  1, 10,  3, 10,  1,  1, 10,  1,  1,  1, 10,  3, 10,  1, 10, 12,
       10,  3, 10,  6,  1, 12, 10,  3, 10,  1,  6,  1, 10,  3,  6,  6,  1,
        1,  1,  1,  1,  1, 10,  9, 10,  3, 10,  6,  6, 10])

## User Data

In [139]:
location = pd.read_csv("0909.csv")
location.tail()

location_id   longitude   latitude  start_date start_time  weekday  \
406          407  121.559666  25.084203  2020-09-09      21:29        4   
407          408  121.560135  25.085544  2020-09-09      22:50        4   
408          409   25.087294  25.087294  2020-09-09      22:50        4   
409          410  121.560943  25.086228  2020-09-09      22:50        4   
410          411  121.562773  25.086631  2020-09-09      22:58        4   

     duration  speed                        name1  \
406       0.0   -1.0  World Gym世界健身俱樂部 台北大直店Sport   
407       0.0   -1.0                          CPC   
408       0.0   -1.0                            家   
409       0.0   -1.0            全聯福利中心Pxmart 內湖文湖   
410       0.0   -1.0                  Family Mart   

                           name2                       name3  \
406  Grand Victoria Hotel Taipei  N°168 Prime Steakhouse 牛排館   
407     Wen Hu Elementary School           全聯福利中心Pxmart 內湖文湖   
408                            4                         NaN   
409     Wen Hu Elementary School                    建安輪胎有限公司   
410                        小鳥不吃肉           全聯福利中心Pxmart 內湖文湖   

                         name4       name5          category1  \
406  Hotel Indigo Taipei North       福莎足球場                gym   
407                 丹特 凹痕回復專門店        來來豆漿        gas_station   
408                        NaN         NaN               home   
409           米其林馳加汽車服務中心(建凱店)  Hilife 萊爾富        supermarket   
410                     佳佳義大利麵        嘉儀電器  convenience_store   

            category2    category3   category4          category5  
406           lodging   restaurant     lodging  point_of_interest  
407    primary_school  supermarket  car_repair         restaurant  
408  entering myPlace          NaN         NaN                NaN  
409    primary_school   car_repair  car_repair  convenience_store  
410        restaurant  supermarket  restaurant              store

In [160]:
stopLoc = location.drop(['category3','category4','category5'], 1)

def string_to_mins(ts):
    a = int(ts.split(':')[0])
    b = int(ts.split(':')[1])
    c = a*60 + b
    return c

#stopLoc['start_time'] = pd.to_datetime(stopLoc['start_time'], format='%H:%M', errors='ignore').apply(string_to_mins)
stopLoc['longitude'] = round(stopLoc['longitude'],3)
stopLoc['latitude'] = round(stopLoc['latitude'],3)
stopLoc

location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.522    25.063  2020-09-08      18:00        3   
4              5    121.522    25.063  2020-09-08      18:00        3   
5              6    121.522    25.063  2020-09-08      18:00        3   
6              7    121.522    25.063  2020-09-08      18:08        3   
7              8    121.522    25.063  2020-09-08      18:08        3   
8              9    121.522    25.063  2020-09-08      18:08        3   
9             10    121.522    25.063  2020-09-08      18:19        3   
10            11    121.522    25.063  2020-09-08      18:19        3   
11            12    121.522    25.063  2020-09-08      18:19        3   
12            13    121.522    25.063  2020-09-08      18:34        3   
13            14    121.522    25.063  2020-09-08      18:34        3   
14            15    121.522    25.063  2020-09-08      18:34        3   
15            16    121.522    25.063  2020-09-08      18:34        3   
16            17    121.536    25.078  2020-09-08      18:56        3   
..           ...        ...       ...         ...        ...      ...   
394          395    121.567    25.085  2020-09-09      19:58        4   
395          396    121.566    25.086  2020-09-09      19:59        4   
396          397    121.566    25.086  2020-09-09      20:03        4   
397          398     25.087    25.087  2020-09-09      20:04        4   
398          399    121.565    25.086  2020-09-09      20:05        4   
399          400    121.563    25.087  2020-09-09      20:07        4   
400          401    121.563    25.087  2020-09-09      20:11        4   
401          402    121.562    25.087  2020-09-09      21:24        4   
402          403    121.561    25.086  2020-09-09      21:24        4   
403          404    121.560    25.086  2020-09-09      21:25        4   
404          405    121.563    25.087  2020-09-09      21:25        4   
405          406    121.560    25.085  2020-09-09      21:25        4   
406          407    121.560    25.084  2020-09-09      21:29        4   
407          408    121.560    25.086  2020-09-09      22:50        4   
408          409     25.087    25.087  2020-09-09      22:50        4   
409          410    121.561    25.086  2020-09-09      22:50        4   
410          411    121.563    25.087  2020-09-09      22:58        4   

     duration     speed                                         name1  \
0         NaN       NaN                                        myhome   
1         NaN       NaN                                         apple   
2         NaN       NaN                                        banana   
3         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
4         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
5         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
6         0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
7         0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
8         0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
9         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
10        0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
11        0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
12        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
13        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
14        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
15        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
16        0.0 -1.000000        National Revolutionary Martyrs' Shrine   
..        ...       ...                                       

In [161]:
#for i in range(50):
#    dropList = []
#     for row in range(1,len(stopLoc)-1): 
#         if stopLoc.iloc[row-1,14] == 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
#             dropList.append(row)
            
#     print(dropList)
#     stopLoc = stopLoc.drop(dropList)
#     stopLoc = stopLoc.reset_index(drop = True)

enterList = []
dropList = []

for a in range(len(stopLoc)):
    
    #如果這筆是「enter」，記住編號
    if (stopLoc.iloc[a,14] == 'entering myPlace'):
        enterList.append(a)
                
    #如果這筆是「exit」，清空enterList
    elif (stopLoc.iloc[a,14] == 'exiting myPlace'):
        enterList = []
            
    elif (enterList == []):
        pass
            
    #如果這筆不是進去也不是出來，且有enterList，為要刪除的東西
    elif (enterList != []):
        dropList.append(a) 

stopLoc = stopLoc.drop(dropList)
stopLoc = stopLoc.reset_index(drop = True)   

[57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 398, 399, 400, 401, 402, 403, 409, 410]


location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.522    25.063  2020-09-08      18:00        3   
4              5    121.522    25.063  2020-09-08      18:00        3   
5              6    121.522    25.063  2020-09-08      18:00        3   
6              7    121.522    25.063  2020-09-08      18:08        3   
7              8    121.522    25.063  2020-09-08      18:08        3   
8              9    121.522    25.063  2020-09-08      18:08        3   
9             10    121.522    25.063  2020-09-08      18:19        3   
10            11    121.522    25.063  2020-09-08      18:19        3   
11            12    121.522    25.063  2020-09-08      18:19        3   
12            13    121.522    25.063  2020-09-08      18:34        3   
13            14    121.522    25.063  2020-09-08      18:34        3   
14            15    121.522    25.063  2020-09-08      18:34        3   
15            16    121.522    25.063  2020-09-08      18:34        3   
16            17    121.536    25.078  2020-09-08      18:56        3   
..           ...        ...       ...         ...        ...      ...   
294          374     25.087    25.087  2020-09-09      17:22        4   
295          388    121.563    25.087  2020-09-09      18:52        4   
296          389    121.567    25.086  2020-09-09      18:53        4   
297          390    121.567    25.086  2020-09-09      18:55        4   
298          391    121.567    25.085  2020-09-09      18:57        4   
299          392    121.567    25.084  2020-09-09      18:58        4   
300          393    121.567    25.083  2020-09-09      19:00        4   
301          394    121.567    25.084  2020-09-09      19:48        4   
302          395    121.567    25.085  2020-09-09      19:58        4   
303          396    121.566    25.086  2020-09-09      19:59        4   
304          397    121.566    25.086  2020-09-09      20:03        4   
305          398     25.087    25.087  2020-09-09      20:04        4   
306          405    121.563    25.087  2020-09-09      21:25        4   
307          406    121.560    25.085  2020-09-09      21:25        4   
308          407    121.560    25.084  2020-09-09      21:29        4   
309          408    121.560    25.086  2020-09-09      22:50        4   
310          409     25.087    25.087  2020-09-09      22:50        4   

     duration     speed                                         name1  \
0         NaN       NaN                                        myhome   
1         NaN       NaN                                         apple   
2         NaN       NaN                                        banana   
3         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
4         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
5         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
6         0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
7         0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
8         0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
9         0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
10        0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
11        0.0 -1.000000                   LOUISA COFFEE 路易莎咖啡 (民權西門市)   
12        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
13        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
14        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
15        0.0 -1.000000            Minquan Zhongshan Rd. Intersection   
16        0.0 -1.000000        National Revolutionary Martyrs' Shrine   
..        ...       ...                                       

In [162]:
#delete trivial data
for i in range(3):
    dropList = []
    for row in range(1,len(stopLoc)-1): 
        if stopLoc.iloc[row,1] == stopLoc.iloc[row-1,1] and stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2]:
            if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
                dropList.append(row)
    
        #compared with the last record, over 2 place name duplicated will be deleted
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        if len(res) > 1: 
            if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
                dropList.append(row)
                
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    
stopLoc

for i in range(3):
    
    dropList = []
    for row in range(1,len(stopLoc)-1): 
        if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
            if stopLoc.iloc[row,1] == stopLoc.iloc[row-1,1] and stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2]:
                dropList.append(row)
    
            #compared with the last record, over 2 place name duplicated will be deleted
            res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
            if len(res) > 1: 
                dropList.append(row)
                
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    
stopLoc



location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.522    25.063  2020-09-08      18:00        3   
4             17    121.536    25.078  2020-09-08      18:56        3   
5             32    121.545    25.080  2020-09-08      18:59        3   
6             33    121.546    25.080  2020-09-08      19:00        3   
7             34    121.547    25.080  2020-09-08      19:00        3   
8             35    121.548    25.080  2020-09-08      19:00        3   
9             36    121.548    25.081  2020-09-08      19:01        3   
10            37    121.549    25.081  2020-09-08      19:01        3   
11            38    121.549    25.082  2020-09-08      19:02        3   
12            39    121.549    25.083  2020-09-08      19:02        3   
13            40    121.549    25.084  2020-09-08      19:02        3   
14            49    121.557    25.085  2020-09-08      19:07        3   
15            51    121.559    25.085  2020-09-08      19:08        3   
16            53    121.560    25.085  2020-09-08      19:11        3   
..           ...        ...       ...         ...        ...      ...   
145          372    121.563    25.084  2020-09-09      17:20        4   
146          373    121.562    25.084  2020-09-09      17:20        4   
147          374     25.087    25.087  2020-09-09      17:22        4   
148          388    121.563    25.087  2020-09-09      18:52        4   
149          389    121.567    25.086  2020-09-09      18:53        4   
150          391    121.567    25.085  2020-09-09      18:57        4   
151          392    121.567    25.084  2020-09-09      18:58        4   
152          393    121.567    25.083  2020-09-09      19:00        4   
153          394    121.567    25.084  2020-09-09      19:48        4   
154          395    121.567    25.085  2020-09-09      19:58        4   
155          396    121.566    25.086  2020-09-09      19:59        4   
156          398     25.087    25.087  2020-09-09      20:04        4   
157          405    121.563    25.087  2020-09-09      21:25        4   
158          406    121.560    25.085  2020-09-09      21:25        4   
159          407    121.560    25.084  2020-09-09      21:29        4   
160          408    121.560    25.086  2020-09-09      22:50        4   
161          409     25.087    25.087  2020-09-09      22:50        4   

     duration      speed                                       name1  \
0         NaN        NaN                                      myhome   
1         NaN        NaN                                       apple   
2         NaN        NaN                                      banana   
3         0.0  -1.000000                 LOUISA COFFEE 路易莎咖啡 (民權西門市)   
4         0.0  -1.000000      National Revolutionary Martyrs' Shrine   
5         0.0   6.282134                                    日本A5和牛專賣   
6         0.0   3.548320                                   福圓號(大直門市)   
7         0.0  10.102074  Taiwan fried chicken founding headquarters   
8         0.0  10.164327                                  好奇營養豆花 大直店   
9         0.0  -1.000000                                      法美園素食館   
10        0.0   3.762866                             迷客夏milkshop 大直店   
11        0.0   8.343172                                  McDonald's   
12        0.0  13.682233                                       布洛烘焙坊   
13        0.0  -1.000000             Taiwanzhongyoudazhizhan Station   
14        0.0   8.225266                                     中山21號廣場   
15        0.0   0.081343                 Grand Victoria Hotel Taipei   
16        0.0   0.697852                        Martial Armour Dazhi   
..        ...        ...                                         ...   
145     

In [163]:
#calculate duration
import datetime as dt
from datetime import datetime

dropList = []
for row in range(0,len(stopLoc)-1): 
        
    res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
    if len(res) > 1: 
        if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
            dropList.append(row)

    #calculate duration
    if stopLoc.iloc[row+1,3] == stopLoc.iloc[row,3]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,4], '%H:%M') - datetime.strptime(stopLoc.iloc[row,4], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,4].split(':')[0]),int(stopLoc.iloc[row+1,4].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,4].split(':')[0]),int(stopLoc.iloc[row,4].split(':')[1]))
        stopLoc.iloc[row,6] = a - b
            
    #kill duration <10
    if pd.Timedelta(stopLoc.iloc[row,6]) < pd.Timedelta('00:10:00'):
        if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
            dropList.append(row)     


removeList = []
for i in range(1,len(dropList)-1):
    if dropList[i] - dropList[i-1] < 3:
        removeList.append(dropList[i])

stopLoc = stopLoc.drop(removeList)
stopLoc = stopLoc.reset_index(drop = True)

for row in range(0,len(stopLoc)-1): 

    #calculate duration
    if stopLoc.iloc[row+1,3] == stopLoc.iloc[row,3]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,4], '%H:%M') - datetime.strptime(stopLoc.iloc[row,4], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,4].split(':')[0]),int(stopLoc.iloc[row+1,4].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,4].split(':')[0]),int(stopLoc.iloc[row,4].split(':')[1]))
        stopLoc.iloc[row,6] = a - b

stopLoc = stopLoc.drop(['start_date','name2','name3','name4','name5','speed'], 1)
stopLoc

location_id  longitude  latitude start_time  weekday        duration  \
0             1    121.576    24.986      11:00        4  1 day, 1:00:00   
1             2    121.443    24.433      12:00        5  1 day, 1:00:00   
2             3    121.123    24.765    13:00\n        6  1 day, 5:00:00   
3             4    121.522    25.063      18:00        3         0:56:00   
4            17    121.536    25.078      18:56        3         0:18:00   
5            57     25.087    25.087      19:14        3         1:46:00   
6            84    121.563    25.087      21:00        3         0:00:00   
7            85    121.567    25.086      21:00        3         0:08:00   
8            94     25.087    25.087      21:08        3         2:29:00   
9           107    121.563    25.087      23:37        3         0:00:00   
10          108    121.561    25.086      23:37        3         0:15:00   
11          144     25.087    25.087      23:52        3        12:26:00   
12          164    121.563    25.087      12:18        4         0:07:00   
13          165    121.562    25.084      12:25        4         0:27:00   
14          244     25.057    25.057      12:52        4         4:02:00   
15          267    121.616    25.057      16:54        4         0:00:00   
16          268    121.617    25.063      16:54        4         0:28:00   
17          374     25.087    25.087      17:22        4         1:30:00   
18          388    121.563    25.087      18:52        4         0:01:00   
19          389    121.567    25.086      18:53        4         0:07:00   
20          393    121.567    25.083      19:00        4         0:48:00   
21          394    121.567    25.084      19:48        4         0:10:00   
22          395    121.567    25.085      19:58        4         0:06:00   
23          398     25.087    25.087      20:04        4         1:21:00   
24          405    121.563    25.087      21:25        4         0:00:00   
25          406    121.560    25.085      21:25        4         0:04:00   
26          407    121.560    25.084      21:29        4         1:21:00   
27          408    121.560    25.086      22:50        4         0:00:00   
28          409     25.087    25.087      22:50        4               0   

                                     name1           category1  \
0                                   myhome                  c1   
1                                    apple                  c1   
2                                   banana                  c1   
3              LOUISA COFFEE 路易莎咖啡 (民權西門市)                cafe   
4   National Revolutionary Martyrs' Shrine  tourist_attraction   
5                                        家                home   
6                                        家                home   
7                           雞吉君拉麵とりよしくん ら麺          restaurant   
8                                        家                home   
9                                        家                home   
10                Wen Hu Elementary School      primary_school   
11                                       家                home   
12                                       家                home   
13                                 北勢湖環保公園                park   
14                                      公司          work place   
15                                      公司          work place   
16          Nanhu Left Bank Riverside Park                park   
17                                       家                home   
18                                       家                home   
19                          雞吉君拉麵とりよしくん ら麺          restaurant   
20                           Sushi Express          restaurant   
21                 TW Haoziwei Ice Factory                food   
22                                醉燈食居-西湖店          restaurant   
23                                       家                home   
24                                       家                home   
25     

In [164]:
for row in range(0,len(stopLoc)-1): 

    #mark as commute if distance bigger than 300 meters. 
    if abs(stopLoc.iloc[row+1,1] - stopLoc.iloc[row,1]) > 0.03 or abs(stopLoc.iloc[row+1,2] - stopLoc.iloc[row,2]) > 0.03:
        if stopLoc.iloc[row,8] != 'entering myPlace':
            stopLoc.iloc[row,7] = 'commute'
        
stopLoc

location_id  longitude  latitude start_time  weekday        duration  \
0             1    121.576    24.986      11:00        4  1 day, 1:00:00   
1             2    121.443    24.433      12:00        5  1 day, 1:00:00   
2             3    121.123    24.765    13:00\n        6  1 day, 5:00:00   
3             4    121.522    25.063      18:00        3         0:56:00   
4            17    121.536    25.078      18:56        3         0:18:00   
5            57     25.087    25.087      19:14        3         1:46:00   
6            84    121.563    25.087      21:00        3         0:00:00   
7            85    121.567    25.086      21:00        3         0:08:00   
8            94     25.087    25.087      21:08        3         2:29:00   
9           107    121.563    25.087      23:37        3         0:00:00   
10          108    121.561    25.086      23:37        3         0:15:00   
11          144     25.087    25.087      23:52        3        12:26:00   
12          164    121.563    25.087      12:18        4         0:07:00   
13          165    121.562    25.084      12:25        4         0:27:00   
14          244     25.057    25.057      12:52        4         4:02:00   
15          267    121.616    25.057      16:54        4         0:00:00   
16          268    121.617    25.063      16:54        4         0:28:00   
17          374     25.087    25.087      17:22        4         1:30:00   
18          388    121.563    25.087      18:52        4         0:01:00   
19          389    121.567    25.086      18:53        4         0:07:00   
20          393    121.567    25.083      19:00        4         0:48:00   
21          394    121.567    25.084      19:48        4         0:10:00   
22          395    121.567    25.085      19:58        4         0:06:00   
23          398     25.087    25.087      20:04        4         1:21:00   
24          405    121.563    25.087      21:25        4         0:00:00   
25          406    121.560    25.085      21:25        4         0:04:00   
26          407    121.560    25.084      21:29        4         1:21:00   
27          408    121.560    25.086      22:50        4         0:00:00   
28          409     25.087    25.087      22:50        4               0   

                                     name1    category1          category2  
0                                   myhome      commute                 c2  
1                                    apple      commute                 c2  
2                                   banana      commute                 c2  
3              LOUISA COFFEE 路易莎咖啡 (民權西門市)         cafe         restaurant  
4   National Revolutionary Martyrs' Shrine      commute    transit_station  
5                                        家         home   entering myPlace  
6                                        家         home    exiting myPlace  
7                           雞吉君拉麵とりよしくん ら麺      commute         university  
8                                        家         home   entering myPlace  
9                                        家         home    exiting myPlace  
10                Wen Hu Elementary School      commute         car_repair  
11                                       家         home   entering myPlace  
12                                       家         home    exiting myPlace  
13                                 北勢湖環保公園      commute         restaurant  
14                                      公司   work place   entering myPlace  
15                                      公司   work place    exiting myPlace  
16          Nanhu Left Bank Riverside Park      commute            parking  
17                                       家         home   entering myPlace  
18                                       家         home    exiting myPlace  
19                          雞吉君拉麵とりよしくん ら麺   restaurant         university  
20                           Sushi Express   restaurant  convenience_store  
21                 TW Haoziwe

## Map Category

In [96]:
stopLoc = pd.merge(stopLoc, loc_to_cat, how='left', on='category1' )
stopLoc = stopLoc.drop(['name1','category1','location_id'],1)
stopLoc['user_id'] = 2
stopLoc = stopLoc[['user_id','weekday','start_time','duration','location']]
stopLoc
#把start_date加回來
#name1,category1拿掉 place_cat對表換成數字

user_id  weekday start_time        duration  location
0         2        4      11:00  1 day, 1:00:00       NaN
1         2        5      12:00  1 day, 1:00:00       NaN
2         2        6    13:00\n        23:10:00       NaN
3         2        6      12:10         5:58:00       5.0
4         2        6      18:08         0:01:00       NaN
5         2        6      18:09         0:20:00       1.0
6         2        6      18:29         0:14:00       NaN
7         2        6      18:43         0:34:00       5.0
8         2        6      19:17         0:58:00      19.0
9         2        6      20:15         0:23:00       NaN
10        2        6      20:38         0:14:00       4.0
11        2        6      20:52         0:18:00       6.0
12        2        6      21:10         0:47:00       NaN
13        2        6      21:57         3:25:00       NaN
14        2        7      01:22        11:12:00       NaN
15        2        7      12:34         0:00:00       1.0
16        2        7      12:34         0:24:00       5.0
17        2        7      12:58         0:01:00       NaN
18        2        7      12:59         0:01:00       1.0
19        2        7      13:00         0:01:00       NaN
20        2        7      13:01         0:06:00       NaN
21        2        7      13:07         0:05:00       1.0
22        2        7      13:12         0:18:00       5.0
23        2        7      13:30         0:03:00       4.0
24        2        7      13:33         4:24:00       NaN
25        2        7      17:57         0:00:00       1.0
26        2        7      17:57         0:35:00       NaN
27        2        7      18:32         0:34:00       NaN
28        2        7      19:06         1:36:00      19.0
29        2        7      20:42         0:21:00       NaN
..      ...      ...        ...             ...       ...
50        2        1      20:27         1:12:00       NaN
51        2        1      21:39         0:00:00       1.0
52        2        1      21:39         0:00:00       NaN
53        2        1      21:39         1:21:00       5.0
54        2        1      23:00        13:33:00       NaN
55        2        2      12:33         0:00:00       1.0
56        2        2      12:33         0:08:00       5.0
57        2        2      12:41         0:14:00       NaN
58        2        2      12:55         0:00:00       1.0
59        2        2      12:55         0:21:00      13.0
60        2        2      13:16         0:00:00       NaN
61        2        2      13:16         0:01:00       NaN
62        2        2      13:17         0:01:00       NaN
63        2        2      13:18         1:06:00       NaN
64        2        2      14:24         2:08:00       NaN
65        2        2      16:32         0:21:00       5.0
66        2        2      16:53         0:00:00       NaN
67        2        2      16:53         0:32:00       NaN
68        2        2      17:25         2:30:00       NaN
69        2        2      19:55         0:00:00       1.0
70        2        2      19:55         0:12:00       NaN
71        2        2      20:07         0:42:00       NaN
72        2        2      20:49         0:53:00       NaN
73        2        2      21:42        12:51:00       NaN
74        2        3      10:33         0:00:00       1.0
75        2        3      10:33         0:19:00       5.0
76        2        3      10:52         0:00:00      13.0
77        2        3      10:52         0:34:00       4.0
78        2        3      11:26         0:26:00       4.0
79        2        3      11:52               0       4.0

[80 rows x 5 columns]

In [ ]:
traing = stopLoc.iloc[:, np.r_[0:4]].values
predictions = clf.predict(traing)

## Myplace

In [ ]:
savedplace = pd.read_csv("savedPlace.csv")
savedplace['place_longitude'] = round(saveplace['place_longitude'],3)
savedplace['place_latitude'] = round(saveplace['place_latitude'],3)
#savedplace = savedplace.loc[savedplace['my_place'] == 1]
savedplace = savedplace.drop(['place_name','my_place','place_id'],1)
savedplace = savedplace.rename(columns={"place_longitude": "longitude", "place_latitude": "latitude"})
savedplace = savedplace.drop_duplicates(subset=['longitude', 'latitude'], keep='last')
savedplace.head()

In [ ]:
stopLoc = pd.merge(stopLoc, savedplace, how='left', on=['longitude','latitude'])
stopLoc