## DATA PREPROCESSING

In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [17]:
df = pd.read_excel("category.xlsx",sheet_name= [1,4])
loc_to_cat = df[1]
loc_to_cat['category1'] = loc_to_cat['category1'].str.lower()
allUserData = df[4]
#userData = [df[3], df[4], df[5], df[6], df[7]]

#for i in userData[1:]:
#    allUserData = allUserData.append(i)
allUserData.head()

user_id  weekday       date start_time   end_date  end_time  duration  \
0        2        2 2020-06-29   16:00:00 2020-06-29  19:00:00  03:00:00   
1        2        2 2020-06-29   19:00:00 2020-06-29  20:00:00  01:00:00   
2        2        2 2020-06-29   20:00:00 2020-06-29  20:30:00  00:30:00   
3        2        2 2020-06-29   20:30:00 2020-06-29  21:30:00  01:00:00   
4        2        2 2020-06-29   21:30:00 2020-06-29  23:30:00  02:00:00   

   category  category_id location_name location_category my_place  \
0   meeting           13           路易莎              cafe      NaN   
1      food            1        全哥鵝肉小炒        restaurant      NaN   
2   leisure           10           NaN               NaN     home   
3  shopping           12       Miramar     Shopping mall      NaN   
4     study            5           NaN               NaN     home   

   location_id  place_id  
0          4.0       NaN  
1          5.0       NaN  
2          NaN       1.0  
3          6.0       NaN  
4          NaN       1.0

In [18]:
allUserData['location']= allUserData['location_id'].combine_first(allUserData['place_id'])
#drop commute
indexNames = allUserData[(allUserData['category_id'] == 17) ].index
allUserData.drop(indexNames,inplace=True)

allUserData['location'].fillna("99", inplace = True)
allUserData = allUserData.drop(['date','end_date','end_time','location_name','location_category','my_place','location_id','place_id'], 1)
allUserData = allUserData.reset_index(drop = True)

In [19]:
def get_hours(ts):
    a = ts.hour
    return a

def get_mins(ts):
    a = ts.minute
    return a

def get_duration(ts):
    a = ts.hour*60 + ts.minute
    return a 

#allUserData['start_mins'] = allUserData['start_time'].apply(get_mins)
allUserData['start_time'] = allUserData['start_time'].apply(get_duration)
allUserData['duration'] = allUserData['duration'].apply(get_duration)
allUserData = allUserData[['user_id','weekday','start_time','duration','location','category','category_id']]
allUserData.tail()

user_id  weekday  start_time  duration location category  category_id
444        2        5          50       495        1    sleep            3
445        2        5         545        15        1  leisure           10
446        2        5         570       150        2     work            6
447        2        5         780       360        3  meeting           13
448        2        5        1200       240        1  leisure           10

## Random Forest Model

In [28]:
train_df = allUserData.loc[0:299]
test_df = allUserData.loc[300:]
print("Number of traing data is :",len(train_df))
print("Number of testing data is :",len(test_df))

Number of traing data is : 300
Number of testing data is : 149


In [29]:
# without diff
X_train = train_df.iloc[:, np.r_[0:4]].values
y_train = train_df.iloc[:, 6].values

X_test = test_df.iloc[:, np.r_[0:4]].values
y_test = test_df.iloc[:, 6].values

In [30]:
clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0,
            warm_start=False)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [31]:
clf.score(X_test, y_test)

0.6308724832214765

In [32]:
imp = clf.feature_importances_
imp

array([0.        , 0.11707604, 0.48461265, 0.3983113 ])

In [26]:
predictions = clf.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.36      0.71      0.48        21
           3       1.00      0.95      0.97        19
           4       0.00      0.00      0.00         0
           6       0.50      0.82      0.62        11
           9       0.80      0.80      0.80         5
          10       0.80      0.71      0.75        58
          11       0.50      0.12      0.20         8
          12       0.44      0.25      0.32        16
          13       1.00      0.33      0.50         6
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         3

   micro avg       0.63      0.63      0.63       149
   macro avg       0.49      0.43      0.42       149
weighted avg       0.67      0.63      0.62       149



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [27]:
print(confusion_matrix(y_test,predictions))

[[15  0  0  0  0  4  1  1  0  0  0]
 [ 0 18  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  1  0  0  0  1  0]
 [ 0  0  0  0  4  1  0  0  0  0  0]
 [ 8  0  1  5  0 41  0  3  0  0  0]
 [ 5  0  0  0  0  2  1  0  0  0  0]
 [10  0  0  0  1  1  0  4  0  0  0]
 [ 0  0  0  4  0  0  0  0  2  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  1  0  0  0]]


In [33]:
predictions

array([12,  1,  1, 10, 10, 10,  3, 10, 10,  1, 10, 11,  1,  1,  4, 10,  3,
       10,  6, 10, 10, 10, 10,  1,  6,  1, 12, 10, 10,  3,  6,  6, 10,  9,
       10,  3,  6,  1,  1, 13, 10, 10,  9, 10,  3,  6,  6,  1, 10, 10,  3,
       10,  1,  1, 12,  1,  1, 11,  1, 10,  3, 10,  3, 10, 12, 12,  1,  6,
        1,  1, 12,  1, 10,  3, 10,  6,  1, 10, 12,  9, 10,  3,  6,  6,  1,
       10,  9, 10, 10,  3, 10,  6,  1, 13,  1,  1,  1, 10, 10,  3, 10,  1,
       16,  1, 10,  3, 10,  1,  1, 10,  1,  1,  1, 10,  3, 10,  1, 10, 12,
       10,  3, 10,  6,  1, 12, 10,  3, 10,  1,  6,  1, 10,  3,  6,  6,  1,
        1,  1,  1,  1,  1, 10,  9, 10,  3, 10,  6,  6, 10])

## User Data

In [3]:
location = pd.read_csv("0830.csv")
location.tail()

location_id   longitude   latitude  start_date start_time  weekday  \
533          534  121.216483  24.963834  2020-08-28      22:46        6   
534          535  121.216791  24.964725  2020-08-28      22:50        6   
535          536  121.216725  24.965684  2020-08-28      22:52        6   
536          537  121.216725  24.964598  2020-08-28      23:00        6   
537          538   25.087458  25.087458  2020-08-30      20:01        1   

     duration  speed           name1               name2  \
533       0.0   -1.0  Guangming Park          藏 Hide Bar   
534       0.0   -1.0      藏 Hide Bar  Hotel Kuva Chateau   
535       0.0   -1.0          亞美豆漿大王              Hilife   
536       0.0   -1.0      藏 Hide Bar      Guangming Park   
537       0.0    0.0             mo家                   4   

                           name3                        name4  \
533  Zhongli Civil Sports Center             中壢國民運動中心全適達泳裝專賣店   
534  Zhongli Civil Sports Center               Guangming Park   
535                   火燒島日式平價居酒屋               WoodHouse 木宅餐館   
536             中壢國民運動中心全適達泳裝專賣店  Zhongli Civil Sports Center   
537                          NaN                          NaN   

                                         name5           category1  \
533                                中壢國民運動中心籃球場  tourist_attraction   
534                           中壢國民運動中心全適達泳裝專賣店                 bar   
535  天成當舖 24H 汽機車黃金鑽石借款 快速放款 工商融資 房屋二胎 勞力士名錶借款          restaurant   
536                         Hotel Kuva Chateau                 bar   
537                                        NaN                Home   

              category2          category3           category4  \
533                 bar  point_of_interest             stadium   
534             lodging  point_of_interest  tourist_attraction   
535   convenience_store         restaurant          restaurant   
536  tourist_attraction            stadium   point_of_interest   
537            entering                NaN                 NaN   

             category5  
533  point_of_interest  
534            stadium  
535            finance  
536            lodging  
537                NaN

In [4]:
stopLoc = location.drop(['category3','category4','category5'], 1)

def string_to_mins(ts):
    a = int(ts.split(':')[0])
    b = int(ts.split(':')[1])
    c = a*60 + b
    return c

#stopLoc['start_time'] = pd.to_datetime(stopLoc['start_time'], format='%H:%M', errors='ignore').apply(string_to_mins)
stopLoc['longitude'] = round(stopLoc['longitude'],3)
stopLoc['latitude'] = round(stopLoc['latitude'],3)
stopLoc

location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.574    25.080  2020-08-27      11:13        5   
4              5    121.574    25.080  2020-08-27      11:13        5   
5              6    121.574    25.080  2020-08-27      11:13        5   
6              7    121.574    25.080  2020-08-27      11:13        5   
7              8    121.574    25.080  2020-08-27      11:37        5   
8              9    121.574    25.080  2020-08-27      11:37        5   
9             10    121.574    25.080  2020-08-27      11:37        5   
10            11    121.569    25.082  2020-08-27      12:09        5   
11            12    121.569    25.082  2020-08-27      12:09        5   
12            13    121.568    25.082  2020-08-27      12:09        5   
13            14    121.566    25.082  2020-08-27      12:10        5   
14            15    121.564    25.083  2020-08-27      12:10        5   
15            16    121.562    25.084  2020-08-27      12:11        5   
16            17    121.561    25.085  2020-08-27      12:11        5   
17            18    121.560    25.085  2020-08-27      12:11        5   
18            19    121.558    25.084  2020-08-27      12:11        5   
19            20    121.556    25.085  2020-08-27      12:12        5   
20            21    121.554    25.085  2020-08-27      12:12        5   
21            22    121.554    25.085  2020-08-27      12:13        5   
22            23    121.551    25.086  2020-08-27      12:13        5   
23            24    121.550    25.086  2020-08-27      12:13        5   
24            25    121.547    25.080  2020-08-27      12:14        5   
25            26    121.546    25.076  2020-08-27      12:15        5   
26            27    121.546    25.075  2020-08-27      12:15        5   
27            28    121.546    25.074  2020-08-27      12:16        5   
28            29    121.547    25.066  2020-08-27      12:18        5   
29            30    121.547    25.066  2020-08-27      12:18        5   
..           ...        ...       ...         ...        ...      ...   
508          509    121.217    24.964  2020-08-28      17:39        6   
509          510    121.217    24.963  2020-08-28      17:41        6   
510          511    121.218    24.962  2020-08-28      17:43        6   
511          512    121.220    24.963  2020-08-28      17:44        6   
512          513    121.221    24.963  2020-08-28      17:46        6   
513          514    121.221    24.962  2020-08-28      17:48        6   
514          515    121.221    24.961  2020-08-28      17:51        6   
515          516    121.221    24.961  2020-08-28      17:51        6   
516          517    121.221    24.962  2020-08-28      19:41        6   
517          518    121.221    24.963  2020-08-28      19:44        6   
518          519    121.219    24.963  2020-08-28      19:46        6   
519          520    121.218    24.962  2020-08-28      19:48        6   
520          521    121.217    24.963  2020-08-28      19:52        6   
521          522    121.217    24.964  2020-08-28      20:02        6   
522          523    121.217    24.964  2020-08-28      20:02        6   
523          524    121.217    24.965  2020-08-28      20:05        6   
524          525    121.215    24.959  2020-08-28      22:03        6   
525          526    121.215    24.959  2020-08-28      22:03        6   
526          527    121.215    24.960  2020-08-28      22:10        6   
527          528    121.215    24.961  2020-08-28      22:13        6   
528          529    121.215    24.961  2020-08-28      22:29        6   
529          530    121.216    24.962  2020-08-28      22:36        6   
530          531    121.215    24.962  2020-08-28      22:43   

In [5]:
for i in range(10):
    dropList = []
    for row in range(1,len(stopLoc)-1): 
        if stopLoc.iloc[row-1,14] == 'entering' and stopLoc.iloc[row,14] != 'exiting':
            dropList.append(row)
            
    print(dropList)
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    
stopLoc    

[39, 138, 143, 147, 177, 312]
[39, 137, 141, 144, 173, 307]
[39, 139, 141, 169, 302]
[39, 138, 139, 166, 298]
[39, 137, 294]
[39, 136, 292]
[39, 135, 290]
[39, 134, 288]
[39, 133, 286]
[39, 132, 284]


location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.574    25.080  2020-08-27      11:13        5   
4              5    121.574    25.080  2020-08-27      11:13        5   
5              6    121.574    25.080  2020-08-27      11:13        5   
6              7    121.574    25.080  2020-08-27      11:13        5   
7              8    121.574    25.080  2020-08-27      11:37        5   
8              9    121.574    25.080  2020-08-27      11:37        5   
9             10    121.574    25.080  2020-08-27      11:37        5   
10            11    121.569    25.082  2020-08-27      12:09        5   
11            12    121.569    25.082  2020-08-27      12:09        5   
12            13    121.568    25.082  2020-08-27      12:09        5   
13            14    121.566    25.082  2020-08-27      12:10        5   
14            15    121.564    25.083  2020-08-27      12:10        5   
15            16    121.562    25.084  2020-08-27      12:11        5   
16            17    121.561    25.085  2020-08-27      12:11        5   
17            18    121.560    25.085  2020-08-27      12:11        5   
18            19    121.558    25.084  2020-08-27      12:11        5   
19            20    121.556    25.085  2020-08-27      12:12        5   
20            21    121.554    25.085  2020-08-27      12:12        5   
21            22    121.554    25.085  2020-08-27      12:13        5   
22            23    121.551    25.086  2020-08-27      12:13        5   
23            24    121.550    25.086  2020-08-27      12:13        5   
24            25    121.547    25.080  2020-08-27      12:14        5   
25            26    121.546    25.076  2020-08-27      12:15        5   
26            27    121.546    25.075  2020-08-27      12:15        5   
27            28    121.546    25.074  2020-08-27      12:16        5   
28            29    121.547    25.066  2020-08-27      12:18        5   
29            30    121.547    25.066  2020-08-27      12:18        5   
..           ...        ...       ...         ...        ...      ...   
468          509    121.217    24.964  2020-08-28      17:39        6   
469          510    121.217    24.963  2020-08-28      17:41        6   
470          511    121.218    24.962  2020-08-28      17:43        6   
471          512    121.220    24.963  2020-08-28      17:44        6   
472          513    121.221    24.963  2020-08-28      17:46        6   
473          514    121.221    24.962  2020-08-28      17:48        6   
474          515    121.221    24.961  2020-08-28      17:51        6   
475          516    121.221    24.961  2020-08-28      17:51        6   
476          517    121.221    24.962  2020-08-28      19:41        6   
477          518    121.221    24.963  2020-08-28      19:44        6   
478          519    121.219    24.963  2020-08-28      19:46        6   
479          520    121.218    24.962  2020-08-28      19:48        6   
480          521    121.217    24.963  2020-08-28      19:52        6   
481          522    121.217    24.964  2020-08-28      20:02        6   
482          523    121.217    24.964  2020-08-28      20:02        6   
483          524    121.217    24.965  2020-08-28      20:05        6   
484          525    121.215    24.959  2020-08-28      22:03        6   
485          526    121.215    24.959  2020-08-28      22:03        6   
486          527    121.215    24.960  2020-08-28      22:10        6   
487          528    121.215    24.961  2020-08-28      22:13        6   
488          529    121.215    24.961  2020-08-28      22:29        6   
489          530    121.216    24.962  2020-08-28      22:36        6   
490          531    121.215    24.962  2020-08-28      22:43   

In [6]:
#delete trivial data
for i in range(3):
    dropList = []
    for row in range(1,len(stopLoc)-1): 
        if stopLoc.iloc[row,1] == stopLoc.iloc[row-1,1] and stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2]:
            if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
                dropList.append(row)
    
        #compared with the last record, over 2 place name duplicated will be deleted
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        if len(res) > 1: 
            if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
                dropList.append(row)
                
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    
stopLoc

location_id  longitude  latitude  start_date start_time  weekday  \
0              1    121.576    24.986  2020/07/22      11:00        4   
1              2    121.443    24.433  2020/07/23      12:00        5   
2              3    121.123    24.765  2020/07/24    13:00\n        6   
3              4    121.574    25.080  2020-08-27      11:13        5   
4             11    121.569    25.082  2020-08-27      12:09        5   
5             13    121.568    25.082  2020-08-27      12:09        5   
6             14    121.566    25.082  2020-08-27      12:10        5   
7             15    121.564    25.083  2020-08-27      12:10        5   
8             16    121.562    25.084  2020-08-27      12:11        5   
9             17    121.561    25.085  2020-08-27      12:11        5   
10            18    121.560    25.085  2020-08-27      12:11        5   
11            19    121.558    25.084  2020-08-27      12:11        5   
12            20    121.556    25.085  2020-08-27      12:12        5   
13            23    121.551    25.086  2020-08-27      12:13        5   
14            25    121.547    25.080  2020-08-27      12:14        5   
15            26    121.546    25.076  2020-08-27      12:15        5   
16            29    121.547    25.066  2020-08-27      12:18        5   
17            31    121.547    25.065  2020-08-27      12:18        5   
18            32    121.545    25.066  2020-08-27      12:19        5   
19            36    121.544    25.063  2020-08-27      12:20        5   
20            37    121.544    25.062  2020-08-27      12:20        5   
21            38    121.544    25.061  2020-08-27      12:21        5   
22            39     25.060    25.060  2020-08-27      12:21        5   
23            50    121.544    25.051  2020-08-27      12:23        5   
24            51    121.544    25.050  2020-08-27      12:23        5   
25            52    121.544    25.049  2020-08-27      12:24        5   
26            53    121.544    25.048  2020-08-27      12:24        5   
27            54    121.544    25.047  2020-08-27      12:24        5   
28            55    121.544    25.045  2020-08-27      12:24        5   
29            56    121.544    25.044  2020-08-27      12:24        5   
..           ...        ...       ...         ...        ...      ...   
211          453    121.214    25.015  2020-08-28      16:09        6   
212          454    121.213    25.014  2020-08-28      16:13        6   
213          456    121.214    25.014  2020-08-28      16:26        6   
214          459    121.212    25.011  2020-08-28      16:33        6   
215          462    121.211    25.009  2020-08-28      16:33        6   
216          465    121.204    25.002  2020-08-28      16:34        6   
217          469    121.201    25.000  2020-08-28      16:36        6   
218          473    121.205    24.993  2020-08-28      16:37        6   
219          479    121.209    24.988  2020-08-28      16:38        6   
220          485    121.216    24.981  2020-08-28      16:39        6   
221          488    121.218    24.974  2020-08-28      16:41        6   
222          489    121.221    24.967  2020-08-28      16:44        6   
223          495    121.220    24.966  2020-08-28      16:51        6   
224          496    121.219    24.966  2020-08-28      16:52        6   
225          497    121.218    24.966  2020-08-28      16:54        6   
226          500    121.217    24.965  2020-08-28      17:00        6   
227          511    121.218    24.962  2020-08-28      17:43        6   
228          512    121.220    24.963  2020-08-28      17:44        6   
229          513    121.221    24.963  2020-08-28      17:46        6   
230          515    121.221    24.961  2020-08-28      17:51        6   
231          518    121.221    24.963  2020-08-28      19:44        6   
232          519    121.219    24.963  2020-08-28      19:46        6   
233          520    121.218    24.962  2020-08-28      19:48   

In [7]:
#calculate duration
import datetime as dt
from datetime import datetime

for i in range(3):
    dropList = []
    for row in range(0,len(stopLoc)-1): 
        
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        if len(res) > 1: 
            if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
                dropList.append(row)

        #calculate duration
        if stopLoc.iloc[row+1,3] == stopLoc.iloc[row,3]:
            stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,4], '%H:%M') - datetime.strptime(stopLoc.iloc[row,4], '%H:%M')       
        else:
            a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,4].split(':')[0]),int(stopLoc.iloc[row+1,4].split(':')[1]))
            b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,4].split(':')[0]),int(stopLoc.iloc[row,4].split(':')[1]))
            stopLoc.iloc[row,6] = a - b
            
        #kill duration <10
        if pd.Timedelta(stopLoc.iloc[row,6]) < pd.Timedelta('00:10:00'):
            if stopLoc.iloc[row,14] != 'entering' and stopLoc.iloc[row,14] != 'exiting':
                dropList.append(row)     
            
    stopLoc = stopLoc.drop(dropList)
    stopLoc = stopLoc.reset_index(drop = True)
    print(dropList)

stopLoc = stopLoc.drop(['start_date','name2','name3','name4','name5','speed'], 1)
stopLoc

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 80, 84, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 153, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 227, 228, 229, 231, 232, 236, 237, 238]
[]
[]


location_id  longitude  latitude start_time  weekday        duration  \
0             1    121.576    24.986      11:00        4  1 day, 1:00:00   
1             2    121.443    24.433      12:00        5  1 day, 1:00:00   
2             3    121.123    24.765    13:00\n        6        22:13:00   
3             4    121.574    25.080      11:13        5         1:08:00   
4            39     25.060    25.060      12:21        5         0:28:00   
5           138     24.987    24.987      12:49        5         0:06:00   
6           141     24.987    24.987      12:55        5         0:01:00   
7           143     24.987    24.987      12:56        5         3:19:00   
8           158    121.577    24.986      16:15        5         3:08:00   
9           174    121.577    24.987      19:23        5         0:06:00   
10          177     24.987    24.987      19:29        5         2:16:00   
11          182    121.577    24.987      21:45        5         0:04:00   
12          188    121.576    24.987      21:49        5         0:50:00   
13          312     25.087    25.087      22:39        5        13:50:00   
14          324    121.563    25.087      12:29        6         0:41:00   
15          403    121.517    25.048      13:10        6         0:44:00   
16          437    121.213    25.014      13:54        6         0:13:00   
17          438    121.214    25.015      14:07        6         1:41:00   
18          447    121.215    25.016      15:48        6         0:25:00   
19          454    121.213    25.014      16:13        6         0:47:00   
20          500    121.217    24.965      17:00        6         0:51:00   
21          515    121.221    24.961      17:51        6         1:57:00   
22          520    121.218    24.962      19:48        6         2:15:00   
23          525    121.215    24.959      22:03        6         0:10:00   
24          528    121.215    24.961      22:13        6         0:47:00   
25          537    121.217    24.965      23:00        6        21:01:00   
26          538     25.087    25.087      20:01        1               0   

                           name1           category1           category2  
0                         myhome                  c1                  c2  
1                          apple                  c1                  c2  
2                         banana                  c1                  c2  
3                  UFC GYM 內科模範館                 gym              school  
4                           mo學校              Others            entering  
5                           mo學校              School            entering  
6                           mo學校              School             exiting  
7                           mo學校              School            entering  
8   National Chengchi University          university          university  
9                           mo宿舍                Dorm             exiting  
10                          mo宿舍                Dorm            entering  
11                          mo宿舍                Dorm             exiting  
12                          mo學校              School             exiting  
13                           mo家                Home            entering  
14                           mo家                Home             exiting  
15                Taipei Station       train_station              bakery  
16                Gloria Outlets       shopping_mall   point_of_interest  
17                Gloria Outlets       shopping_mall          shoe_store  
18  The Big Pier 大碼頭美式手抓海鮮餐廳 中壢店          restaurant   point_of_interest  
19                Gloria Outlets       shopping_mall          restaurant  
20                       十三張紅油抄手                food             lodging  
21                      坐著做。壽司本店          restaurant          restaurant  
22                Guangming Park  tourist_attraction   convenience_store  
23                      7-Eleven   convenience_store  tourist_attraction  


## Map Category

In [ ]:
stopLoc = pd.merge(stopLoc, loc_to_cat, how='left', on='category1' )
stopLoc = stopLoc.drop(['name1','category1','location_id'],1)
stopLoc['user_id'] = 2
stopLoc = stopLoc[['user_id','weekday','start_time','duration','location']]
stopLoc
#把start_date加回來
#name1,category1拿掉 place_cat對表換成數字

In [ ]:
traing = stopLoc.iloc[:, np.r_[0:4]].values
predictions = clf.predict(traing)

## Myplace

In [ ]:
savedplace = pd.read_csv("savedPlace.csv")
savedplace['place_longitude'] = round(saveplace['place_longitude'],3)
savedplace['place_latitude'] = round(saveplace['place_latitude'],3)
#savedplace = savedplace.loc[savedplace['my_place'] == 1]
savedplace = savedplace.drop(['place_name','my_place','place_id'],1)
savedplace = savedplace.rename(columns={"place_longitude": "longitude", "place_latitude": "latitude"})
savedplace = savedplace.drop_duplicates(subset=['longitude', 'latitude'], keep='last')
savedplace.head()

In [ ]:
stopLoc = pd.merge(stopLoc, savedplace, how='left', on=['longitude','latitude'])
stopLoc