## DATA PREPROCESSING

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df = pd.read_excel("category1.xlsx",sheet_name= [0,1,2,3,4,5,6,7])

In [3]:
allUserData = df[3]
userData = [df[3], df[4], df[5], df[6], df[7]]

for i in userData[1:]:
    allUserData = allUserData.append(i)

In [4]:
allUserData['location']= allUserData['location_id'].combine_first(allUserData['place_id'])
allUserData['location'].fillna("99", inplace = True)
allUserData = allUserData.drop(['date','location_name','location_category','my_place','location_id','place_id'], 1)

In [5]:
def tomins(ts):
    a = ts.hour*60 + ts.minute
    return a

allUserData['start_time'] = allUserData['start_time'].apply(tomins)
allUserData['end_time'] = allUserData['end_time'].apply(tomins)
allUserData['duration'] = allUserData['duration'].apply(tomins)

allUserData.tail()

user_id  weekday  start_time  end_time  duration category  category_id  \
69        5        5           0        45        45     home            2   
70        5        5          45       470       425    sleep            3   
71        5        5         470       490        20     food            1   
72        5        5         490       565        75  commute           17   
73        5        5         565       810       245     work            6   

   location  
69        1  
70        1  
71        1  
72       99  
73        3

In [6]:
cols = allUserData.columns
for col in cols:
    print(col)

user_id
weekday
start_time
end_time
duration
category
category_id
location


## Random Forest Model

In [7]:
train_df = allUserData[allUserData['weekday'] < 4]
test_df = allUserData[allUserData['weekday'] >= 4]
print("Number of traing data is :",len(train_df))
print("Number of testing data is :",len(test_df))

Number of traing data is : 193
Number of testing data is : 246


In [8]:
# without diff
X_train = train_df.iloc[:, np.r_[0:4, 7]].values
y_train = train_df.iloc[:, 6].values

X_test = test_df.iloc[:, np.r_[0:4, 7]].values
y_test = test_df.iloc[:, 6].values

In [9]:
clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0,
            warm_start=False)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [10]:
clf.score(X_test, y_test)

0.8008130081300813

In [11]:
imp = clf.feature_importances_
imp

array([0.07474598, 0.03433832, 0.23517535, 0.21636921, 0.43937114])

In [19]:
predictions = clf.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.59      0.67      0.62        30
           2       0.85      0.99      0.91        72
           3       1.00      0.82      0.90        33
           4       1.00      0.75      0.86         4
           5       0.00      0.00      0.00         6
           6       0.74      1.00      0.85        14
           8       0.00      0.00      0.00         5
           9       0.50      0.11      0.18         9
          10       0.00      0.00      0.00         3
          11       0.33      0.67      0.44         3
          12       0.00      0.00      0.00         0
          13       0.50      0.40      0.44         5
          16       0.50      0.67      0.57         6
          17       0.93      0.96      0.95        55
          18       0.00      0.00      0.00         1

   micro avg       0.80      0.80      0.80       246
   macro avg       0.46      0.47      0.45       246
weighted avg       0.76   

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [20]:
print(confusion_matrix(y_test,predictions))

[[20  2  0  0  0  0  0  0  0  3  1  0  3  1  0]
 [ 0 71  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  4 27  0  0  1  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  4  0  0  0  0  0  0  0  1  0  1  0  0  0]
 [ 0  0  0  0  0 14  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  1  0  1  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  1  0  1  0  0  1  1  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 1  0  0  0  0  0  0  0  0  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  2  0  0  0  0  0  2  0  0  0]
 [ 1  1  0  0  0  0  0  0  0  0  0  0  4  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0 53  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [21]:
predictions

array([ 2,  2,  3,  2, 17,  1, 17,  1, 17,  2, 17,  1, 17,  2,  2,  2,  2,
        3,  2, 17, 13, 17,  2,  2,  3,  1,  2,  2,  2,  2,  3,  2,  2,  2,
        3,  2,  1,  1, 17,  2, 17,  4, 17,  2,  3,  2, 17,  6,  1,  6, 17,
        2, 17,  4, 17,  9,  2,  2,  3,  2, 17,  6,  1,  6, 17, 13, 17,  2,
        2,  3,  2, 17,  6,  1,  6, 17, 13,  1, 17, 17,  2,  2,  3,  2, 17,
        1,  1, 17,  1,  1, 12,  9, 17,  2,  2,  3, 17,  6, 17,  1,  6, 17,
       17,  4, 17,  2,  2,  3, 17,  6,  2,  2,  3,  1,  2,  2,  2, 13, 11,
       17,  2,  2,  3,  2,  6,  2,  2,  3,  2, 17,  6, 17,  2,  2,  3,  2,
        1,  2,  2,  2,  3, 17, 12,  6,  1, 17,  2,  2,  3,  2, 17,  6,  1,
        6, 17,  2, 11,  2,  2,  3,  2, 17,  6, 11, 17,  2,  2,  3, 16, 16,
       17,  1,  1,  1, 17,  1, 11,  2,  2,  3,  2,  2,  2,  2,  6, 11, 17,
        2,  2,  3, 16,  2, 17,  6,  1,  6, 17,  1, 17,  2,  2,  3, 16, 17,
        1, 17, 17, 17,  2,  2,  3, 16, 17,  1,  1, 17,  1, 17,  1,  2,  2,
        3, 16, 17,  1,  1

In [223]:
location = pd.read_csv("location.csv")
location

location_id   longitude   latitude           start_time      duration  \
0              1  121.576000  24.986000                  NaN           NaN   
1              2  121.443000  24.433000                  NaN           NaN   
2              3  121.123000  24.765000                  NaN      3.677109   
3              4  121.576839  24.986453  2020/07/16 16:50:30      0.742091   
4              5  121.576855  24.986461  2020/07/16 18:37:11   3432.180398   
5              6  121.581536  25.009585  2020/07/16 19:34:23      0.763942   
6              7  121.581536  25.009585  2020/07/16 19:34:23    126.488363   
7              8  121.574330  25.027316  2020/07/16 19:36:29      0.912132   
8              9  121.574330  25.027316  2020/07/16 19:36:29      1.012450   
9             10  121.558394  25.084939  2020/07/16 21:53:54    198.142266   
10            11  121.559879  25.084624  2020/07/16 21:57:12      1.495238   
11            12  121.529165  25.040675  2020/07/17 11:51:34     94.169944   
12            13  121.527204  25.033525  2020/07/17 11:53:08      0.682123   
13            14  121.527204  25.033525  2020/07/17 11:53:08    337.173567   
14            15  121.530656  25.029291  2020/07/17 11:58:45      0.663661   
15            16  121.530656  25.029291  2020/07/17 11:58:45  18724.143795   
16            17  121.565912  25.034518  2020/07/17 17:10:49      0.977636   
17            18  121.565912  25.034518  2020/07/17 17:10:49    183.142022   
18            19  121.567769  25.035710  2020/07/17 17:13:52      0.709243   
19            20  121.567769  25.035710  2020/07/17 17:13:52   2631.127076   
20            21  121.560457  25.034858  2020/07/17 17:57:43      0.686588   
21            22  121.560457  25.034858  2020/07/17 17:57:43     47.145825   
22            23  121.559893  25.033422  2020/07/17 17:58:30      0.517593   
23            24  121.559893  25.033422  2020/07/17 17:58:30    206.155231   
24            25  121.548871  25.033155  2020/07/17 18:01:56      0.647864   
25            26  121.548871  25.033155  2020/07/17 18:01:56    391.153719   
26            27  121.543840  25.033055  2020/07/17 18:08:27      0.981934   
27            28  121.543840  25.033055  2020/07/17 18:08:27      0.940561   
28            29  121.562977  25.087257  2020/07/19 19:45:49      1.370772   
29            30  121.563026  25.087327  2020/07/19 20:08:59   5162.472775   
..           ...         ...        ...                  ...           ...   
84            85  121.592003  25.082074     2020/07/22 17:31     27.649459   
85            86  121.592003  25.082074     2020/07/22 17:31    431.156957   
86            87  121.578892  25.078600     2020/07/22 17:31    431.781617   
87            88  121.578892  25.078600     2020/07/22 17:38    185.155048   
88            89  121.575903  25.079839     2020/07/22 17:38    185.955862   
89            90  121.575903  25.079839     2020/07/22 17:41     51.171766   
90            91  121.573542  25.080594     2020/07/22 17:41     51.671403   
91            92  121.573542  25.080594     2020/07/22 17:41    194.170617   
92            93  121.569461  25.081950     2020/07/22 17:41    194.859436   
93            94  121.569461  25.081950     2020/07/22 17:44     53.172343   
94            95  121.567263  25.082120     2020/07/22 17:44     53.638895   
95            96  121.567263  25.082120     2020/07/22 17:44     71.166910   
96            97  121.565673  25.082089     2020/07/22 17:44     71.685429   
97            98  121.565673  25.082089     2020/07/22 17:45     26.169403   
98            99  121.563929  25.082908     2020/07/22 17:47     26.784825   
99           100  121.563929  25.082908     2020/07/22 17:47     48.166794   
100          101  121.561990  25.083794     2020/07/22 17:47     48.626875   
101          102  121.561990  25.083794     2020/07/22 17:47    465.066912   
102          103  121.562966  25.087142     2020/07/22 17:47    465.811442   
103          104  121.56296

In [224]:
stopLoc = location.drop(['location_id','longitude','latitude','category2','category3','category4','category5'], 1)
stopLoc = stopLoc.reset_index(drop=True)

In [227]:
dropList = []

for row in range(1,len(stopLoc)-1):
    res = set(stopLoc.iloc[row,3:8]) & set(stopLoc.iloc[row-1,3:8])
    
    if len(res) > 1:
        dropList.append(row)
    
    if (stopLoc.iloc[row-1,2] > 3) & (stopLoc.iloc[row+1,2] > 3):
        dropList.append(row)
    
stopLoc = stopLoc.drop(dropList) 

In [228]:
stopLoc = stopLoc.loc[stopLoc['speed'] < 0]
stopLoc = stopLoc.reset_index(drop = True)
stopLoc

start_time      duration  speed  \
0   2020/07/16 16:50:30      0.742091   -1.0   
1   2020/07/16 19:34:23    126.488363   -1.0   
2   2020/07/16 19:36:29      1.012450   -1.0   
3   2020/07/17 11:53:08    337.173567   -1.0   
4   2020/07/17 11:58:45  18724.143795   -1.0   
5   2020/07/17 17:10:49    183.142022   -1.0   
6   2020/07/17 17:13:52   2631.127076   -1.0   
7   2020/07/17 17:57:43     47.145825   -1.0   
8   2020/07/17 17:58:30    206.155231   -1.0   
9   2020/07/17 18:01:56    391.153719   -1.0   
10  2020/07/17 18:08:27      0.940561   -1.0   
11  2020/07/19 19:45:49      1.370772   -1.0   
12  2020/07/19 21:35:02    931.130793   -1.0   
13  2020/07/19 21:50:33   4087.137069   -1.0   
14  2020/07/19 22:58:49  49231.222766   -1.0   
15  2020/07/20 12:43:42    281.169387   -1.0   
16  2020/07/20 12:48:23    170.159108   -1.0   
17  2020/07/20 12:51:13    566.170191   -1.0   
18  2020/07/20 13:00:39     19.153576   -1.0   
19  2020/07/20 13:00:58     37.169557   -1.0   
20  2020/07/20 13:01:35    615.592798   -1.0   
21  2020/07/20 13:11:51      1.449480   -1.0   
22  2020/07/20 20:23:38   1250.170408   -1.0   
23  2020/07/20 20:44:28   1828.815027   -1.0   
24  2020/07/20 21:14:57    659.167525   -1.0   
25  2020/07/20 21:25:56    243.170011   -1.0   
26  2020/07/20 21:29:59     90.167989   -1.0   
27  2020/07/20 21:31:29    569.165178   -1.0   
28  2020/07/20 21:41:00    882.704370   -1.0   
29  2020/07/20 21:55:43   7510.141875   -1.0   
30  2020/07/21 00:00:53    157.111371   -1.0   
31  2020/07/21 00:03:30     56.173301   -1.0   
32     2020/07/21 14:48     33.246924   -1.0   
33     2020/07/22 17:16    121.167298   -1.0   
34     2020/07/22 17:18    197.167663   -1.0   
35     2020/07/22 17:21    104.172003   -1.0   
36     2020/07/22 17:22    494.149354   -1.0   
37     2020/07/22 17:31     27.157387   -1.0   
38     2020/07/22 17:31    431.156957   -1.0   
39     2020/07/22 17:38    185.155048   -1.0   
40     2020/07/22 17:41     51.171766   -1.0   
41     2020/07/22 17:41    194.170617   -1.0   
42     2020/07/22 17:44     53.172343   -1.0   
43     2020/07/22 17:44     71.166910   -1.0   
44     2020/07/22 17:45     26.169403   -1.0   
45     2020/07/22 17:47     48.166794   -1.0   
46     2020/07/22 17:47    465.066912   -1.0   
47     2020/07/22 17:54    331.491168   -1.0   
48     2020/07/22 18:17    465.156863   -1.0   
49     2020/07/22 18:47    443.166899   -1.0   
50     2020/07/23 09:10    671.167887   -1.0   
51     2020/07/23 09:31    214.173828   -1.0   
52     2020/07/23 09:34      0.000000   -1.0   

                                                name1  \
0                                              國立政治大學   
1                                              土地公嶺古道   
2                                                北星寶宮   
3                                               蜜密牛軋餅   
4                                                金華公園   
5                                                微風南山   
6                                         NIKE Neo19店   
7                                               溫州鮮餛飩   
8                                      台北國際會議中心(TICC)   
9                                                雞二拉麵   
10                                                大安站   
11                                         全家便利商店 文湖店   
12                                           蓬萊高爾夫練習場   
13                        World Gym世界健身俱樂部 台北大直店Sport   
14                                           軟訊資訊有限公司   
15                                              捷運港墘站   
16                                                文德站   
17                                          華南銀行 內湖分行   
18  蒸霸王東湖店 東湖創始店/內湖蒸氣火鍋/東湖美食/內湖美食/內湖海鮮塔推薦/內湖海鮮餐廳推薦...   
19                                     台灣中油康寧站(加盟&自助)   
20                                               明湖國小   
21                                                餡老滿   
22                                       IKEA宜家家居 敦北店   
23                                              春美冰菓